### PR TITLE
android buildbot fix for android pt2 thanks to sonninnos for buildbot information

### PR DESCRIPTION
**Pull request by grant2258**
Git is going a bit crazy for me today keeps on putting pull requests to master instead of the 255 branch. 

Lua needs the env var so we have to change it to export it in the makefile. I also added a dir check to make sure the ndk directory exists. but the env var not being available is causing the issue of clang not being found.

### CODE REVIEW

**Comment by grant2258** [comment]
@sonninnos  ok after looking up a  master build seems the buildbot is setting the ndk root variable ive added the checks to fix that. (master) setting it too ANDROID_NDK_ROOT="/android-sdk-linux/ndk/22.0.7026061 this should 100% work for buildbot now as im grabbing that var and setting it to what we need

**Comment by sonninnos** [comment]
Ehh, for some reason buildbot isn't starting to build this like it did yesterday..

**Comment by grant2258** [comment]
I noticed the buildbot was still running when i looked at the buildbot for the old build you linked. The mac build said something about instability contact admin. Perhaps that old  job needs deleted and the new one triggered. If you mean there is an error with this makefile I can certainly look at any errors.

**Comment by sonninnos** [comment]
Nah I don't think anything is wrong with this commit, just the gitlab thing is acting out since it was updated yesterday at the same time when the old pipelines were running..

**Comment by grant2258** [comment]
I did notice a small issue that thankfully doesnt fail on other builds. Checking for a blank directory passes and it works as it should when its set as well. This wont effect anything apart from running the check when it shouldnt Ill fix it after the build bots stable dont want to interrupt the build bot. 

https://github.com/libretro/mame/blob/87df0daaedf75abd03635d6b143d4d09e4384aa5/Makefile.libretro#L166

should be
```
ifneq ($(ANDROID_NDK_HOME),)
```

**Comment by sonninnos** [comment]
Cool, the android runs passed! Massive thanks for sorting this thing out! I'll wait until the pipeline finishes before merging 0.255.

https://git.libretro.com/libretro/mame/-/pipelines/204445

**Comment by grant2258** [comment]
Only edited a few lines in the makefile you done the real work here. The pipeline links you really helped me to debug what was going on without havng to guess . Im Just glad its working.

**Comment by grant2258** [comment]
Just one point of note its more a suggestion than anything else. It would be worthwhile adding a tag going forward for two reasons

1) Git describe will need it for core info
2) its easy for a user to compile a older version

git tag -fa lrmame0256 or any other way you would like to do it

**Comment by sonninnos** [comment]
Sure why not, but should it be done after or before the PR merge?

**Comment by grant2258** [comment]
git tag -fa will put the tag at the current commit so after would probably be ideal either will work though

**Comment by sonninnos** [comment]
I was rather thinking if the tag should be on the PR already so that there is no need to hassle afterwards. I tagged the current state also as 0.251. Quite a bunch of tags are missing in between, but it is what it is.

**Comment by grant2258** [comment]
sounds like a plan I think you need to push the tags with git push --tags as the tags dont automatically push afaik. Its just me being picky anyway I just like tags to switch between versions

**Comment by sonninnos** [comment]
Sorry to bother you again, but might you have any idea why ios-arm64 is failing after the merge, even though the merged branch had the same changes as the test branch, which passed..?

```
Undefined symbols for architecture arm64:
  "bfm_bd1_device::AT_BLANK", referenced from:
      bfm_bd1_device::blank(int) in libbfm.a(bfm_bd1.o)
  "bfm_bd1_device::AT_NORMAL", referenced from:
      bfm_bd1_device::blank(int) in libbfm.a(bfm_bd1.o)
      bfm_bd1_device::write_char(int) in libbfm.a(bfm_bd1.o)
  "bfm_bda_device::AT_BLANK", referenced from:
      bfm_bda_device::blank(int) in libbfm.a(bfm_bda.o)
  "bfm_bda_device::AT_NORMAL", referenced from:
      bfm_bda_device::device_reset() in libbfm.a(bfm_bda.o)
      bfm_bda_device::blank(int) in libbfm.a(bfm_bda.o)
      bfm_bda_device::write_char(int) in libbfm.a(bfm_bda.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
https://git.libretro.com/libretro/mame/-/pipelines/204547

**Comment by grant2258** [comment]
src/mame/bfm/bfm_bda.h:39:	static const uint8_t AT_BLANK   = 0x02;
src/mame/bfm/bfm_bd1.cpp:241:		std::fill(std::begin(m_attrs), std::end(m_attrs), AT_BLANK);
src/mame/bfm/bfm_bd1.cpp:247:			std::fill_n(m_attrs + m_window_start, m_window_size, AT_BLANK);
src/mame/bfm/bfm_bd1.cpp:254:			std::fill_n(m_attrs, m_window_start, AT_BLANK);
src/mame/bfm/bfm_bd1.cpp:256:			std::fill_n(m_attrs + m_window_end, (16 - m_window_end), AT_BLANK);
src/mame/bfm/bfm_bd1.h:42:	static const uint8_t AT_BLANK   = 0x02;
src/mame/bfm/bfm_bda.cpp:169:		std::fill(std::begin(m_attrs), std::end(m_attrs), AT_BLANK);
src/mame/bfm/bfm_bda.cpp:175:			std::fill_n(m_attrs + m_window_start, m_window_size, AT_BLANK);
src/mame/bfm/bfm_bda.cpp:183:			std::fill_n(m_attrs + 0, m_window_start, AT_BLANK);
src/mame/bfm/bfm_bda.cpp:184:			std::fill_n(m_attrs + m_window_end, (16 - m_window_end), AT_BLANK);


It looks like it doesnt like the variable being defined inside the header for some reason have you tried with static inline ?  Wasnt an issue before not sure whats changed. You could change it to an enum or move it into the cpp file as a work around if static inline doesnt do the trick.

**Comment by grant2258** [comment]
```
diff --git a/src/mame/bfm/bfm_bd1.h b/src/mame/bfm/bfm_bd1.h
index 2d0b735535e..b11dcff7249 100644
--- a/src/mame/bfm/bfm_bd1.h
+++ b/src/mame/bfm/bfm_bd1.h
@@ -37,10 +37,10 @@ protected:
 	virtual void device_post_load() override;
 
 private:
-	static const uint8_t AT_NORMAL  = 0x00;
-	static const uint8_t AT_FLASH   = 0x01;
-	static const uint8_t AT_BLANK   = 0x02;
-	static const uint8_t AT_FLASHED = 0x80;   // set when character should be blinked off
+	static inline const uint8_t AT_NORMAL  = 0x00;
+	static inline const uint8_t AT_FLASH   = 0x01;
+	static inline const uint8_t AT_BLANK   = 0x02;
+	static inline const uint8_t AT_FLASHED = 0x80;   // set when character should be blinked off
 
 	std::unique_ptr<output_finder<16> > m_outputs;
 	uint8_t m_port_val;
diff --git a/src/mame/bfm/bfm_bda.h b/src/mame/bfm/bfm_bda.h
index cea0da23c06..29e118f1ee9 100644
--- a/src/mame/bfm/bfm_bda.h
+++ b/src/mame/bfm/bfm_bda.h
@@ -34,10 +34,10 @@ protected:
 	virtual void device_post_load() override;
 
 private:
-	static const uint8_t AT_NORMAL  = 0x00;
-	static const uint8_t AT_FLASH   = 0x01;
-	static const uint8_t AT_BLANK   = 0x02;
-	static const uint8_t AT_FLASHED = 0x80;   // set when character should be blinked off
+	static inline const uint8_t AT_NORMAL  = 0x00;
+	static inline const uint8_t AT_FLASH   = 0x01;
+	static inline const uint8_t AT_BLANK   = 0x02;
+	static inline const uint8_t AT_FLASHED = 0x80;   // set when character should be blinked off
 
 	std::unique_ptr<output_finder<16> > m_outputs;
 	std::unique_ptr<output_finder<1> > m_brightness;

```

**Comment by grant2258** [comment]
hold on ill edit it i removed some of the const in the second one *fixed now*

looking at the build 

DSDLMAME_NO_X11 -DRETROMAME -DUSE_XINPUT=0 -DOSD_RETRO -DSDLMAME_UNIX -DRETROMAME_UNIX -DSDLMAME_MACOSX -DSDLMAME_DARWIN -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DNO_USE_MIDI -DNO_USE_PORTAUDIO -DNO_USE_BGFX -DUSE_QTDEBUG=0 -DUSE_OPENGL=0

are all missing something changed in the build ci somewhere

**Pull request merged**
