### PR TITLE
fix the video issues with gnw artwork

### LINKED ISSUE #288: Game & Watch and Tiger Hanhelds are too slow (unless alternate render method is used)
When loading those games normally, with their artwork, they run at 50-60% speed on my i5 4670.

In the standalone version they run fine.

The only way for these to run at full speed in RetroArch is to enable "alternate rendering method" and then choose a lower resolution, which completely mangles the prerendered LCD graphics of those devices.

### PR DESCRIPTION
**Pull request by ghost**
This is the last of the fixed that where pointed out to me apart from the vertical shaders. 

the fixes https://github.com/libretro/mame/issues/288

### CODE REVIEW

**Comment by stuken** [comment]
This completely breaks with alt renderer disabled. Nothing will boot with it set to off and if loaded and switched to the viewport shrinks each frame to nothing.

Edit: This only seems to apply for non 4:3 ratio games. Multi monitor and tate screen games freeze.

**Comment by LibretroAdmin** [comment]
@stuken Sorry to hear that. I will revert this for now.

@JasmiJiveBunny Could you possibly try to make a revised version of this that addresses the issues that @stuken pointed out? Thanks. You can send a new PR once these issues have been rectified.

**Comment by ghost** [comment]
can you be more specific what games are freezing. So i can reproduce what are you using the alt render off for is it some kind of switchres use? I see there is an issue Ill sort it at the weekend. What I need to know is this alt mode false which is the alt mode. Do we want integer scaling on this or aspect scaling,

**Comment by stuken** [comment]
From my testing Darius II (Triple screen), Namco Classic Collection Vol. 2 and Dodonpachi Saidaioujou all lock up with alt renderer off. In addition the screen scaling for Darius II is very different to master. It looks almost like an integer scaling mode where it only fills about 70-80% of the width of the screen.

**Comment by ghost** [comment]
@stuken the issue im having is one machine has no issues and i tried it on another machine and seen some. I dont understand the use case of the alt render. When alt render is one that default mame behaviour. So i would need to know the case use for this other alt render is 0. I cant fix it if I dont know what it actually should be doing different

**Comment by stuken** [comment]
Looks like alt renderer on with a 640x360 res gives identical results to alt off with these changes. Stripping out alt altogether probably makes sense if the exising behaviour can be mantintained and the gnw issues can be fixed.

**Comment by ghost** [comment]
The only reason I can see for this code is to return integer scaling for switch res. If thats what is require its easily fixed its just set to look right for normal case use. The main problem this alt mode doesnt do a abounds check and artwork need that. The res is set extremely hi on calculations thats why the alt res off was failing. I assumed this was for crt users so its hard coded to 640 x 480. I need to move the hard coding of framebuffer if we want to get more creative.

**Comment by ghost** [comment]
@LibretroAdmin  is there any way to get the current set aspect ratio and and resolution(viewport) from libretro?

**Comment by ghost** [comment]
@stuken I forgot to mention when testing reset res or alternating  modes rest the game in mame after the change. Previously it was constantly calling geometry update regardless if if was needed or not constantly. It is aspect ratio related im guessing you using a 16:9 aspect monitor 800 x 450, 1024 x 576 are should be golden for you.  If we cant get aspect information of the monitor we might need to a core option for it

**Comment by stuken** [comment]
Sorry, was very tired last night and kind of said the opposite of what I was talking about :). Like you suggest making alt the default now might be the way forward. The non alt mode can be replicated using alt so stripping out that config and code path while keeping the rest of your changes should be fine.

**Comment by LibretroAdmin** [comment]
> @LibretroAdmin is there any way to get the current set aspect ratio and and resolution(viewport) from libretro?

I dont think so no - you would have to add new environment callbacks to libretro.h and then implement it in retroarch and send the PRs to us.

**Comment by ghost** [comment]
@stuken The core is setup to locked at 4:3 the way it is now that does need looking at there is no need it.  I cant see any issues in fixing this up at all. 

The game and watch is an upstream issue Ill open an issue there and let them know about it. I will patch it in our resize code until they do fix it though.

@LibretroAdmin  thats ok it would be better for users if they didnt have to set things manually ill put an your monitors aspect option in the core and a list of width resolutions. We can set the height from the width they select that way.

**Pull request merged**
