### PR TITLE
version bump: mame 0.215

### PR DESCRIPTION
**Pull request by tcamargo**

### CODE REVIEW

**Comment by tcamargo** [comment]
FYI. Last commit was cherry picked from mame master branch.

**Comment by Cereal-Killa** [comment]
Looking forward to test this with a 0.215 rom set, do you happen to have the compiled binaries for this so that I can try it?

**Comment by tcamargo** [comment]
I only have a Linux binary. 

https://camargo.batocera.org/libretro-mame/

**Comment by Cereal-Killa** [comment]
> I only have a Linux binary.
> 
> https://camargo.batocera.org/libretro-mame/

Thanks man, looking for a Windows binary, now that this got merged it will show up on the retroarch buildbot tomorrow?

**Comment by hizzlekizzle** [comment]
Yeah, should be sometime in the next few hours to a day

**Comment by Tatsuya79** [comment]
It failed, Linux x64 log:
http://paste.libretro.com/172123

**Comment by Cereal-Killa** [comment]
Indeed, I can see the [last Windows build](https://buildbot.libretro.com/nightly/windows/x86_64/latest/) available is from the 12nd, Travis seems to be [failing for a while](https://travis-ci.org/libretro/mame/builds?utm_medium=notification&utm_source=github_status)? And [could not find this merge](https://ci.appveyor.com/project/startaq/mame/history) on AppVeyor.

**Comment by Tatsuya79** [comment]
...but win x64 just succeeded. :eyes:

edit:it will be uploaded to the buildbot later, when the compilation cycle for everything windows is done.

**Comment by Cereal-Killa** [comment]
> ...but win x64 just succeeded. 👀

My bad, I don't know where to find it, could you share the link?

**Comment by tcamargo** [comment]
> It failed, Linux x64 log:
> http://paste.libretro.com/172123

I will take a look because I got no problems with linux. I don't have a windows environment/toolchain.

**Comment by tcamargo** [comment]
> Indeed, I can see the [last Windows build](https://buildbot.libretro.com/nightly/windows/x86_64/latest/) available is from the 12nd, Travis seems to be [failing for a while](https://travis-ci.org/libretro/mame/builds?utm_medium=notification&utm_source=github_status)? And [could not find this merge](https://ci.appveyor.com/project/startaq/mame/history) on AppVeyor.

Travis CI is failing for a long time. Even before my first version bump.

**Comment by tcamargo** [comment]
````
mame: [Status: done] [recipes/windows/cores-windows-x64_seh-generic] [Finished: 2019-11-18 10:54:19.821285+00:00] []
mame: [Status: fail] [recipes/linux/cores-linux-arm7neonhf] [Finished: 2019-11-18 08:34:36.643632+00:00] [http://paste.libretro.com/172142]
mame: [Status: fail] [recipes/linux/cores-linux-x64-generic] [Finished: 2019-11-18 06:48:38.923831+00:00] [http://paste.libretro.com/172123]
mame: [Status: fail] [recipes/android/cores-android-armv7-ndk-mame] [Finished: 2019-11-18 03:23:51.002299+00:00] [http://paste.libretro.com/172098]
````
Linux worked for me. I will check it first.

**Comment by Cereal-Killa** [comment]
Where do I find the windows-x64 artifacts?

**Comment by tcamargo** [comment]
Linux problem
````
Compiling src/lib/netlist/analog/nld_bjt.cpp...
g++    -MMD -MP -MP -D__LIBRETRO__ -DNDEBUG -DPTR64=1 -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DPUGIXML_HEADER_ONLY -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -D__STDC_CONSTANT_MACROS -I"../../../../../src/lib" -I"../../../../../src/lib/netlist"  -O2 -m64 -fPIC -pipe -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-error=deprecated-declarations -Wno-unused-result -Wno-array-bounds -m64 -std=c++14 -Woverloaded-virtual -Wsuggest-override -include /home/buildbot/buildbot/linux_x86_64/libretro-mame/src/osd/libretro/retroprefix.h -o "../../../../libretro/obj/x64/libretro/src/lib/netlist/analog/nld_bjt.o" -c "../../../../../src/lib/netlist/analog/nld_bjt.cpp"
../../../../../src/lib/netlist/analog/nld_bjt.cpp: In instantiation of 'netlist::analog::nld_QBJT_switch::nld_QBJT_switch(CLASS&, const pstring&) [with CLASS = netlist::netlist_state_t; pstring = pstring_t<putf8_traits>]':
../../../../../src/lib/netlist/plib/pmempool.h:219:57:   required from 'plib::mempool::unique_pool_ptr<T> plib::mempool::make_unique(Args&& ...) [with T = netlist::analog::nld_QBJT_switch; Args = {netlist::netlist_state_t&, const pstring_t<putf8_traits>&}; plib::mempool::unique_pool_ptr<T> = std::unique_ptr<netlist::analog::nld_QBJT_switch, plib::arena_deleter<plib::mempool, netlist::analog::nld_QBJT_switch> >]'
../../../../../src/lib/netlist/nl_factory.h:90:47:   required from 'netlist::unique_pool_ptr<netlist::device_t> netlist::factory::device_element_t<C>::Create(netlist::netlist_state_t&, const pstring&) [with C = netlist::analog::nld_QBJT_switch; netlist::unique_pool_ptr<netlist::device_t> = std::unique_ptr<netlist::device_t, plib::arena_deleter<plib::mempool, netlist::device_t> >; pstring = pstring_t<putf8_traits>]'
../../../../../src/lib/netlist/analog/nld_bjt.cpp:446:1:   required from here
../../../../../src/lib/netlist/analog/nld_bjt.cpp:185:39: error: invalid initialization of reference of type 'const pstring& {aka const pstring_t<putf8_traits>&}' from expression of type 'const char*'
    , m_state_on(*this, "m_state_on", 0)
                                       ^
../../../../../src/lib/netlist/analog/nld_bjt.cpp:137:80: note: in passing argument 3 of 'netlist::analog::nld_QBJT::nld_QBJT(CLASS&, const pstring&, const pstring&) [with CLASS = netlist::netlist_state_t; pstring = pstring_t<putf8_traits>]'
../../../../../src/lib/netlist/analog/nld_bjt.cpp: In instantiation of 'netlist::analog::nld_QBJT_EB::nld_QBJT_EB(CLASS&, const pstring&) [with CLASS = netlist::netlist_state_t; pstring = pstring_t<putf8_traits>]':
../../../../../src/lib/netlist/plib/pmempool.h:219:57:   required from 'plib::mempool::unique_pool_ptr<T> plib::mempool::make_unique(Args&& ...) [with T = netlist::analog::nld_QBJT_EB; Args = {netlist::netlist_state_t&, const pstring_t<putf8_traits>&}; plib::mempool::unique_pool_ptr<T> = std::unique_ptr<netlist::analog::nld_QBJT_EB, plib::arena_deleter<plib::mempool, netlist::analog::nld_QBJT_EB> >]'
../../../../../src/lib/netlist/nl_factory.h:90:47:   required from 'netlist::unique_pool_ptr<netlist::device_t> netlist::factory::device_element_t<C>::Create(netlist::netlist_state_t&, const pstring&) [with C = netlist::analog::nld_QBJT_EB; netlist::unique_pool_ptr<netlist::device_t> = std::unique_ptr<netlist::device_t, plib::arena_deleter<plib::mempool, netlist::device_t> >; pstring = pstring_t<putf8_traits>]'
../../../../../src/lib/netlist/analog/nld_bjt.cpp:446:1:   required from here
../../../../../src/lib/netlist/analog/nld_bjt.cpp:229:16: error: invalid initialization of reference of type 'const pstring& {aka const pstring_t<putf8_traits>&}' from expression of type 'const char*'
   , m_alpha_r(0)
                ^
../../../../../src/lib/netlist/analog/nld_bjt.cpp:137:80: note: in passing argument 3 of 'netlist::analog::nld_QBJT::nld_QBJT(CLASS&, const pstring&, const pstring&) [with CLASS = netlist::netlist_state_t; pstring = pstring_t<putf8_traits>]'
netlist.make:1447: recipe for target '../../../../libretro/obj/x64/libretro/src/lib/netlist/analog/nld_bjt.o' failed
make[3]: *** [../../../../libretro/obj/x64/libretro/src/lib/netlist/analog/nld_bjt.o] Error 1
Makefile:25: recipe for target 'netlist' failed
make[2]: *** [netlist] Error 2
make[2]: *** Waiting for unfinished jobs....
Compiling src/osd/libretro/window.cpp...
```

**Comment by tcamargo** [comment]
I can't replicated that error. Main difference to my machine is that i use gcc 8.3 instead of gcc 5.5.
@Tatsuya79 would you know how can I access logs from successful builds?

**Comment by tcamargo** [comment]
Forgot about this announcement:

https://www.mamedev.org/?p=474

> Updated Requirements
24 Oct 2019
The upcoming MAME 0.215 release will be the last version that can be compiled with GCC 5 or GCC 6. Going forward, the minimum supported compiler will be GCC 7.2 or clang 5. The Windows development tools have included GCC 7.4 for some time already, so you won’t need to update unless you haven’t in a very long time.
MAME 0.217 will be the last release with pre-built 32-bit Windows binaries supplied. Starting in 2020, you’ll need to compile MAME yourself if you want a 32-bit version. We’ll still support building for 32-bit architectures, but optimisation for 32-bit x86 will not be a priority.

So, they probably already removed support for gcc 5. @twinaphex Would be possible to upgrade gcc in buildbot?

**Comment by inactive123** [comment]
Pretty bad decisions they are making, I especially don't agree with the removal of 32bit. Fortunately, it looks like we can just compile continue compiling that ourselves, and in case they ever do drop it, there's always the various other older MAME cores.

As for the older GCC version on the buildbot, we are migrating to a new server pretty soon, it will likely sort itself out within the next two months.

**Comment by Cereal-Killa** [comment]
Just making sure I understood, in the meantime there won't be any updated build of the MAME core until that migration gets completed?

**Comment by inactive123** [comment]
It only doesn't compile on Linux right now?

**Comment by Cereal-Killa** [comment]
> It only doesn't compile on Linux right now?

Actually a new Windows binary just popped up on the nightly build
directory and it's up to date with this pull request, thank you!

1otMwCSwII

**Comment by tcamargo** [comment]
> It only doesn't compile on Linux right now?

It builds on my toolchain (gcc8). 

I got some logs from discord:

- Windows seems fine
mame: [Status: done] [recipes/windows/cores-windows-x64_seh-generic] [Finished: 2019-11-18 10:54:19.821285+00:00] []

- Errors on linuxes. Both using gcc5.
mame: [Status: fail] [recipes/linux/cores-linux-arm7neonhf] [Finished: 2019-11-18 08:34:36.643632+00:00] [http://paste.libretro.com/172142]
mame: [Status: fail] [recipes/linux/cores-linux-x64-generic] [Finished: 2019-11-18 06:48:38.923831+00:00] [http://paste.libretro.com/172123]

- Android gets a different error. I think it was already failing before. 
mame: [Status: fail] [recipes/android/cores-android-armv7-ndk-mame] [Finished: 2019-11-18 03:23:51.002299+00:00] [http://paste.libretro.com/172098]

i could not find an osx build log.

**Pull request merged**
