### PR TITLE
Version bump: 0.214

### PR DESCRIPTION
**Pull request by tcamargo**
Besides the normal merge procedure, I had to correct osd_get_clipboard_text signature in osdlib_retrp.cpp.

### CODE REVIEW

**Comment by Tatsuya79** [comment]
It's failing to build on [windows ](http://paste.libretro.com/166155)and [osx ](http://paste.libretro.com/166072)now.

**Comment by tcamargo** [comment]
Checking...

**Comment by tcamargo** [comment]
Need to implement/define a new function in osd/libretro/window.cpp (osd_set_aggressive_input_focus). 

https://github.com/tcamargo/mame/commit/2bc887ee849906582878fdbb734dcfdb0732b3bd

@Tatsuya79 @twinaphex I don't have a build setup for mac and win to test this change. Would be possible to use RA buildbot?

**Comment by Tatsuya79** [comment]
That did the trick. :+1:

**Comment by Tatsuya79** [comment]
Would you happen to know how to fix that new crash that came with the updated source?
https://github.com/libretro/mame/issues/122
Any cps1 games such as Final Fight or sf2 will crash atm.

And we had that one too a bit back:
https://github.com/libretro/mame/issues/76

**Comment by tcamargo** [comment]
I will take a look. Have you tried cps1 on 0.212?

**Comment by Tatsuya79** [comment]
Yes it was working fine before.

**Comment by tcamargo** [comment]
@Tatsuya79 Ok. I will continue the discussion in https://github.com/libretro/mame/issues/122.

**Pull request merged**
