### PR TITLE
Update to MAME 0.222

### PR DESCRIPTION
**Pull request by rtissera**

### CODE REVIEW

**Comment by inactive123** [comment]
Thanks for this rebase!

**Comment by inactive123** [comment]
Hi there, the build is now broken (at least on Windows) -

http://paste.libretro.com/215018

The libretro MAME core should not build in any audio driver dependencies from MAME like Xaudio and whatnot except for the actual Libretro audio implementation instead (which usually tends to be just a stub driver anyway).

**Comment by rtissera** [comment]
@twinaphex ah crap, I tested only Linux/x64, I will have a look on it tonight.
Thanks for the build log.
Another user reported build failure on ARM platforms due to missing AsmJit ARM implementation.

**Comment by inactive123** [comment]
Alright, thanks for wanting to look into it. Appreciated.

**Pull request merged**
