### PR TITLE
More resolutions for the alternate renderer.

### PR DESCRIPTION
**Pull request by Tatsuya79**
Hope that works as is, I don't have what's needed to compile and test it.

#34

### CODE REVIEW

**Comment by r-type** [comment]
For now the video buffer is limited to 1600X1200 so not enough to hold your résolution.

**Comment by r-type** [comment]
Maybe we can raise to 1920*1080 , need to change here L71 and  L577 
```
#ifdef M16B
uint16_t videoBuffer[1600*1200];
#define LOG_PIXEL_BYTES 1
#else
unsigned int videoBuffer[1600*1200];
#define LOG_PIXEL_BYTES 2*1
#endif

...

//FIXME: re-add way to handle 16/32 bit
#ifdef M16B
    memset(videoBuffer, 0, 1600*1200*2);
#else
    memset(videoBuffer, 0, 1600*1200*2*2);
#endif

```

**Comment by Tatsuya79** [comment]
Well, you know better than me!
I'll do what you think is OK. 🐱

**Comment by Tatsuya79** [comment]
I saw you did a commit for that, closing this one.

**Pull request closed without merging**
