### PR TITLE
libretro os should not be changed to platform

### PR DESCRIPTION
**Pull request by grant2258**
quick fix for builds until i redo the makefile. This can be pulled at any point your ready

### CODE REVIEW

**Comment by grant2258** [comment]
@sonninnos done a little digging I can see the problem and where it is. do a 
```
 git difftool -d  lrmame0251 -- scripts/toolchain.lua  `
```
near the bottom you can see the link options have changed. Ive never messed with lua before ill try pick the syntax up looks basic like :).  Is a trivial fix for anyone that knows the syntax of lua though. The sane fix would be for retroarch to include the shared dll with the retroarch apk imho. Thats what the docs suggest. 

try adding PRECOMPILE=1 to the platform flags fot the android builds that failing might  get you past the mtime issue

**Comment by sonninnos** [comment]
Yep I also noticed that the file got cleaned up a bit too much, so I tried adding some things back now. And looks like it should be lowercase `precompile`.

**Comment by grant2258** [comment]
Ill put a fix in for new new toolchains when its done . The code there will only work in ndk 22 and below ad libgcc was removed in 23b. Are the macos builds working fine ?

**Comment by sonninnos** [comment]
Cool. No way to test, and no one has complained yet..

**Comment by grant2258** [comment]
ill compile a bin and test just cant find any logs will let you know if its boots or not i mean the android builds have no maccy stuff. Well reinstalled Ra the logs are working this time not sure why.
```
RetroArch 1.15.0 (Git 227a9ec)
=== Build =======================================
Capabilities: ASIMD 
[INFO] Version: 1.15.0
[INFO] Git: 227a9ec
[INFO] Built: Jul 13 2023
[INFO] =================================================
[Input]: Found input driver: "android".
[Core]: Loading dynamic libretro core from: "/data/user/0/com.retroarch/cores/mamearcade_libretro_android.so"
Failed to open libretro core: "/data/user/0/com.retroarch/cores/mamearcade_libretro_android.so"
Error(s): dlopen failed: library "libc++_shared.so" not found: needed by /data/user/0/com.retroarch/cores/mamearcade_libretro_android.so in namespace classloader-namespace
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core symbols..
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version of libretro API: 1, Compiled against API: 1
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 960x720.
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.5
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x7bcf09b880.
[GL]: Vendor: Qualcomm, Renderer: Adreno (TM) 650.
[GL]: Version: OpenGL ES 3.2 V@0502.0 (GIT@193b2ee, I593c16c433, 1633593732) (Date:10/07/21).
[GL]: Using resolution 810x1734.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 768, Blocks = 32, Total = 24576 ...
[Audio]: Started synchronous audio driver.
[Display]: Found display driver: "gl".
Failed to open libretro core: "/data/user/0/com.retroarch/cores/mamearcade_libretro_android.so"
Error(s): dlopen failed: library "libc++_shared.so" not found: needed by /data/user/0/com.retroarch/cores/mamearcade_libretro_android.so in namespace classloader-namespace
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_music_history.lpl".
[Playlist]: Loading history file: "/storage/emulated/0/Android/data/com.retroarch/files/content_image_history.lpl".
[Playlist]: Loading favourites file: "/storage/emulated/0/Android/data/com.retroarch/files/content_favorites.lpl".
```
tested from https://git.libretro.com/libretro/mame/-/jobs/3871076 

looks like we missed
linkoptions {
			"-nostdlib",
		}

ill compile locally and make sure it works before putting a pull request in

**Comment by grant2258** [comment]
got arm and ar64 working need to test x86 and x64 then ill put a req in

**Comment by grant2258** [comment]
I think that's everything in order. There are some cleanups that can be done another time. 

Libretto_cpu and libretro_os are not needed at all and ill remove them in time.  The mac builds can be cached at your discretion the logs told me what I needed to know to get it fixed. OSX might cause you come issues because the both arm64 and x64 set the platfrom to osx. Thankfully arm64 sets cross_build variable to tell it apart from the x64. 

You might want to review the nproc calculation on the mac on the CI other builds are using 6 and the macs are using 2,  thats why they are so slow at building. Just @ me if there is any issues, or something that is broke. I dont actively subscribe to projects my emails spammy enough already! Nice to see the core back on the road again!

**Comment by sonninnos** [comment]
Weird how now after simply enabling macosx caches, all androids started failing with:
```
error: PCH file was compiled for the target 'x86_64-none-linux-android24' but the current translation unit is being compiled for target 'x86_64-unknown-linux-android24'
```

```
error: PCH file was compiled for the target 'thumbv7-none-linux-android24' but the current translation unit is being compiled for target 'thumbv7-unknown-linux-android24'
```

```
error: PCH file was compiled for the target 'aarch64-none-linux-android24' but the current translation unit is being compiled for target 'aarch64-unknown-linux-android24'
```

**Comment by grant2258** [comment]
I mentioned the target was changed earlier they just need a clean compile. 
https://github.com/libretro/mame/pull/410#issuecomment-1655336577

**Comment by sonninnos** [comment]
Ah yes, great, whoops. I got permissions to cancel and retry pipelines, and also to clear the cache, which indeed seemed to have worked.

**Comment by grant2258** [comment]
About android the some are missing the mess builds in the ci  Android ARMv7a and x64 are missing mess and x86 isint compiling at all (it never was but support was added if needed) not sure if there is even any need for the x86 builds at all though just letting you know.

**Pull request merged**
