### PR TITLE
libretro/mame 0.232

### PR DESCRIPTION
**Pull request by tcamargo**

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Thanks for all of your work on  this, tcamargo!

**Comment by rtissera** [comment]
great work, looking forward to see it merged

**Comment by hizzlekizzle** [comment]
Sorry it took me so long to test, but I'm getting this error at runtime (compiles fine):

`undefined symbol: _ZN14memory_manager8allocateER23device_memory_interface`

**Comment by Tasosgemah** [comment]
Is there something that prevents this to be merged?

**Comment by hizzlekizzle** [comment]
@Tasosgemah just the error I'm getting, AFAIK. If anyone can confirm/disconfirm/solve the issue, we can move forward with it.

**Comment by Sanaki** [comment]
Compiled and ran fine on my machine. Just did a quick test with Road Blaster, I'm sure there are better tests to be done. I did compile with gcc-10 using `ARCHOPTS=-U_FORTIFY_SOURCE` in case that makes any difference.

**Comment by Tasosgemah** [comment]
> 
> 
> Compiled and ran fine on my machine. Just did a quick test with Road Blaster, I'm sure there are better tests to be done. I did compile with gcc-10 using `ARCHOPTS=-U_FORTIFY_SOURCE` in case that makes any difference.

I could spend some time testing a lot of games if you could share the compiled file.

**Comment by hizzlekizzle** [comment]
Alright, sounds good! I think we're clear to merge it, then.

**Comment by Tasosgemah** [comment]
So, does anyone have a compiled file yet that can share? Downloader is still stuck on version 0.230. MAME also released version 0.233 today.

**Comment by inactive123** [comment]
Merged, sorry for it taking so long.

**Comment by Tasosgemah** [comment]
> 
> 
> Merged, sorry for it taking so long.

Strange, the downloader still gets the 0.230 version.

**Pull request merged**
