### PR TITLE
Update to 0.246

### PR DESCRIPTION
**Pull request by stuken**
Update to 0.246. Needed a small rejigging of some header imports to match the upstream changes but nothing major.

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
HI @kwyxz, can you confirm if this works on Haiku?

**Comment by StormedBubbles** [comment]
Hey, somewhere in the .245 update was a change that switched the generated .so for lr-mess from `mess_libretro.so` to `mamemess_libretro.so` for my Raspberry Pi. I can still compile, but the installation script for RetroPie users "fails" because it can't find the file with the right name. I just had to move it manually from my temporary folder and rename. Was that name change intentional? If so, I'll request a change in the RetroPie-Setup script.

**Comment by stuken** [comment]
Thats a change from upstream. Makefile generation has significantly changed since 0244 and there is no specific mess subtarget script anymore. It's all built dynamically through python and lua scripts and the target names are concatenations of target and subtarget. Changing it here is probably not the best idea.
https://github.com/mamedev/mame/tree/mame0244/scripts/target/mame

**Comment by kwyxz** [comment]
> HI @kwyxz, can you confirm if this works on Haiku?

I am not sure mame_libretro ever built on Haiku, so it should not be a blocker for a merge. But I will give it a try.

**Comment by kwyxz** [comment]
Yeah it doesn't build on Haiku because it does not recognize the running OS, we could probably work around this but I never took the time and it's a patch that would make more sense upstream. I'll try and clear some time to work on this at some point but it should not be a blocker for this merge request.

```
In file included from ../../src/host/os_chdir.c:7:
../../src/host/premake.h:39:10: fatal error: windows.h: No such file or directory
   39 | #include <windows.h>
      |          ^~~~~~~~~~~
compilation terminated.
genie.make:415: recipe for target 'obj/Release/src/host/os_chdir.o' failed
make[2]: *** [obj/Release/src/host/os_chdir.o] Error 1
make[2]: Leaving directory '/boot/home/mame/3rdparty/genie/build/gmake.linux'
makefile:1572: recipe for target '3rdparty/genie/bin/linux/genie' failed
make[1]: *** [3rdparty/genie/bin/linux/genie] Error 2
make[1]: Leaving directory '/boot/home/mame'
Makefile.libretro:242: recipe for target 'build' failed
make: *** [build] Error 2
```

**Pull request merged**
