### PR TITLE
Buildbot ios fix attempt

### PR DESCRIPTION
**Pull request by grant2258**
@sonninnos libretro_os and  libretro_cpu and other where not being passed along to genie thats been fixed. I just noticed it when I was looking at the conditions in the file. 

Ilso fixed ip the darwin makefile to not break upstream x86 builds" disabled the -m32 and -m64 for retro builds only since its only arm builds been done. Since the lua scripts where never called with the libretro options, this will probably fix any issues you where having. Thats me finished with this can test any time.

### CODE REVIEW

**Comment by joepogo** [comment]
Great work on all of this @grant2258 ! I just tried updating from the buildbot on Xbox retroarch and it still says .251. Does this fix attempt help Xbox uwp at all?

**Comment by grant2258** [comment]
@joepogo you can grab the windows build here https://git.libretro.com/libretro/mame/-/jobs/3843399/artifacts/browse two mac builds are failing atm.

**Comment by sonninnos** [comment]
Ready to merge?

**Comment by grant2258** [comment]
Yes it is hopefully we get somewhere not sure what image is used for docker so i cant test locally unfortunately. It might be better to make a new branch and only compile the problem builds on there. It wont clobber the buildbot that way. Also make sure the cache is cleared for a clean build

**Comment by sonninnos** [comment]
Ok here goes. `.gitlab-ci.yml` reveals again what image is used: https://git.libretro.com/libretro-infrastructure/ci-templates

**Comment by grant2258** [comment]
I did check the tvos it didnt reference any image file. The build running now will fail as its using the cache needs a clean build with the changes

**Comment by joepogo** [comment]
Thanks @grant2258 ! Is this a temporary place to grab the dll or will it eventually build through the buildbot and we can grab it through the online updater for Xbox?

**Comment by sonninnos** [comment]
I have no idea how to trigger the cache clean, other than removing caches from `.gitlab-ci.yml`.

And unfortunately even more started failing: https://git.libretro.com/libretro/mame/-/pipelines/205105

**Comment by grant2258** [comment]
yes this will fix that pull request I put in will fix that failure its PTR64 need set.

**Pull request merged**
