### PR TITLE
Update 0.272

### PR DESCRIPTION
**Pull request by sonninnos**

### CODE REVIEW

**Comment by riggles1** [comment]
Core breaking bug in this one, regarding MAME button mappings not saving like they should, default.cfg reverting between different games, created an issue for it. Appreciate it!

**Comment by sonninnos** [comment]
All seems fine here.

**Comment by riggles1** [comment]
The issue is weirder, so it works like it should for everything else except sfiii3.zip.

When testing more, sfiii3.zip, any other street fighter, perfectly fine, loads default.cfg mame button configs. Tried a bunch of games, but with sfiii3.zip it just sets it's own mame navigation mappings. Really weird.

No .cfg's present for sfiii3.zip, no clones or anything, verified that it loads sfiii3.zip with the MAME (current) core.

I'm spooked out.

**Comment by riggles1** [comment]
Aaah, found it, this game has a core override (option override .opt where it probably wasn't reading the mame ini or something), idk if that override changed or something but ugh. I play SFIII a ton and it was working right before this, so idk why it has an override suddenly, from where? So I was blinded by being too sure about that.

Thanks! It's 2AM, I didn't even think of that.

**Comment by riggles1** [comment]
Yeah checked my backup, for some reason "mame_read_config = "disabled" was set for SFIII3, in the .opt.

This didn't matter with 270, works with that opt present, but it does matter with 272, so something did change there that wasn't on my part.

But this seems like expected behavior, but good to keep in mind if people have old .opt files lurking about in their config folder and start experiencing button mapping issues.

**Pull request merged**
