### PR TITLE
Update to 0.170

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
I fixed some merge conflicts, but it's broken yet.

### CODE REVIEW

**Comment by r-type** [comment]
where does it break ?
i managed to get a 0.170 working (at least for linux X64 ) using a new fresh fork from mamedev.
( in my git not here) .
only only need few changes , 
like change .c to .cpp 
or like change 
ui_input_push_char_event(machine(), our_target, (unicode_char)ui_ipt_pushchar); 
to
 machine().ui_input().push_char_event( our_target, (unicode_char)ui_ipt_pushchar);

**Comment by sergiobenrocha2** [comment]
I did that in the last commit. It's just I'm getting errors with < exception > and others headers. Maybe it's just my system's gcc broken, I don't know.

**Comment by r-type** [comment]
Not exactly , you simply comment the ui_input_push_char stuff !

BTW no <execption> error is  that you compile c file with c compiler but include some c++ header .
as it #include "emu.h" in  libretro.c and retromain.c 

change libretro.c and retromain.c to libretro.cpp and retromain.cpp , and 
it should build fine like in my mame repo.

**Comment by sergiobenrocha2** [comment]
Ok, it's building!!!

@r-type , are you getting this? Tried with CPS-2 game:

```
retroarch: ../../../../../src/emu/render.cpp:2426: render_manager::~render_manager(): Assertion `m_live_textures == 0' failed.
Aborted (core dumped)
```

**Comment by sergiobenrocha2** [comment]
The core dumped only happens if you have the artwork folder, see #42

**Comment by r-type** [comment]
what you mean by using artwork folder ?
with the version on my repo , i have artwork folder in retrosysdir/mame/artwork
and cps2 or others games works fine and don't crash at exit.

**Comment by sergiobenrocha2** [comment]
Yeah, your fork is not crashing, weird. And the patch you applied seems not to be exactly what there's in this repo.

**Comment by r-type** [comment]
it's not really older implementation , it's aim to be a minimal patch to run Mame on libretro.
it's the sequel of what i did when i start here a port  of mame for libetro  . After it was heavily modified so not aimed to be a shallow fork (as i wanted)  ,so i 've started to maintain it on my repo.

**Comment by fr500** [comment]
actually the one that wanted to make all those changes was tjcarter IIRC,
changing the buildsystem and all, we wanted mame git to be stable and as
shallow as possible to be able to keep it always up-to-date

**Comment by twinaphex** [comment]
Yeah, tjcarter just wasted our time for months with his stuff and eventually even betrayed us.

**Comment by sergiobenrocha2** [comment]
I see. Good catch.

**Comment by twinaphex** [comment]
OK, so what do we do now? sergiobenrocha2 - can you backport the remaining things that need to be added from r-type's repo or should we try to rebase against r-type's repo entirely maybe in the future?

**Comment by r-type** [comment]
i don't see really many things to add from my repo , but instead cleanup some of here.

- like remove the remaining MKCHAMP  HISCORE in some emu/ src files .
and removing unused files like /src/osd/retro/retro.mak
or orphan define like REGRESSION_TESTING
 
maybe you can try  little change to lua script like 

```
diff --git a/Makefile.libretro b/Makefile.libretro
index f214cc4..e44aba6 100644
--- a/Makefile.libretro
+++ b/Makefile.libretro
@@ -125,7 +125,7 @@ endif
 #
 ###########################################################################
 
-BUILDFLAGS = REGENIE=$(REGENIE) VERBOSE=$(VERBOSE) NOWERROR=$(NOWERROR)
+BUILDFLAGS = REGENIE=$(REGENIE) VERBOSE=$(VERBOSE) NOWERROR=$(NOWERROR) OSD="retro"
 ifneq ($(PYTHON_EXECUTABLE),)
 	BUILDFLAGS += PYTHON_EXECUTABLE=$(PYTHON_EXECUTABLE)
 endif
diff --git a/scripts/src/main.lua b/scripts/src/main.lua
index 7d61ff3..5595213 100644
--- a/scripts/src/main.lua
+++ b/scripts/src/main.lua
@@ -105,14 +105,14 @@ end
 		includedirs {
 			MAME_DIR .. "src/osd/retro/libretro-common/include",
 		}
-		links { "libco" }
+--		links { "libco" }
 
 		-- Workaround: Compile the public libretro API into the shlib
 		-- rather than the OSD to keep linkers from being "helpful"
 		-- and stripping it out.
-		files {
-			MAME_DIR .. "src/osd/retro/libretro.cpp"
-		}
+--		files {
+--			MAME_DIR .. "src/osd/retro/libretro.cpp"
+--		}
 
 		-- Ensure the public API is made public with GNU ld
 		if _OPTIONS["targetos"]=="linux" then
diff --git a/scripts/src/osd/retro.lua b/scripts/src/osd/retro.lua
index 82494d7..2e823c2 100644
--- a/scripts/src/osd/retro.lua
+++ b/scripts/src/osd/retro.lua
@@ -65,7 +65,8 @@ project ("osd_" .. _OPTIONS["osd"])
 		MAME_DIR .. "src/osd/retro/libretro-common/include",
 	}
 
-	files {
+	files {	
+		MAME_DIR .. "src/osd/retro/libretro-common/libco/libco.c",
 		MAME_DIR .. "src/osd/osdnet.cpp",
 		MAME_DIR .. "src/osd/modules/netdev/taptun.cpp",
 		MAME_DIR .. "src/osd/modules/netdev/pcap.cpp",
@@ -75,7 +76,7 @@ project ("osd_" .. _OPTIONS["osd"])
 		MAME_DIR .. "src/osd/modules/lib/osdobj_common.cpp",
 		MAME_DIR .. "src/osd/modules/sound/none.cpp",
 		MAME_DIR .. "src/osd/modules/sound/retro_sound.c",
-		MAME_DIR .. "src/osd/retro/retromain.cpp",
+	--	MAME_DIR .. "src/osd/retro/retromain.cpp",
 
 		-- The public API in libretro.c is "unused" and tends to get
 		-- stripped by the "helpful" linker, so we compile it into
@@ -162,7 +163,6 @@ project ("ocore_" .. _OPTIONS["osd"])
 
 	files {
 		MAME_DIR .. "src/osd/osdcore.cpp",
-		MAME_DIR .. "src/osd/modules/osdmodule.cpp",
 		MAME_DIR .. "src/osd/modules/font/font_none.cpp",
 		MAME_DIR .. "src/osd/modules/lib/osdlib_retro.c",
 		MAME_DIR .. "src/osd/modules/midi/none.cpp",
@@ -183,14 +183,14 @@ project ("ocore_" .. _OPTIONS["osd"])
 		}
 	end
 
-project ("libco")
-	uuid (os.uuid("libco"))
-	kind "StaticLib"
+--project ("libco")
+--	uuid (os.uuid("libco"))
+--	kind "StaticLib"
 
-	includedirs {
-		MAME_DIR .. "src/osd/retro/libretro-common/include",
-	}
+--	includedirs {
+--		MAME_DIR .. "src/osd/retro/libretro-common/include",
+--	}
 
-	files {
-		MAME_DIR .. "src/osd/retro/libretro-common/libco/libco.c",
-	}
+--	files {
+--		MAME_DIR .. "src/osd/retro/libretro-common/libco/libco.c",
+--	}
```
and try to see if machine().render().target_free(our_target); in void retro_osd_interface::osd_exit()
can help to solve #42

**Comment by twinaphex** [comment]
Alright, let's just merge this, then apply the diff patches r-type sent.

**Comment by twinaphex** [comment]
Alright @r-type and @sergiobenrocha2 , I merged the PR and I backported r-type's suggestions -

https://github.com/libretro/mame/commit/5c77f67e39224c79df49fb9a48c6e0b8d19d2a1f

https://github.com/libretro/mame/commit/0405554f58a08749e6f870ddc0031c4d5b967c67

Can you check out if this fixed the remaining issues?

**Comment by sergiobenrocha2** [comment]
It's working well.

**Pull request merged**
