### PR TITLE
update

### PR DESCRIPTION
**Pull request by wings110**

### CODE REVIEW

**Comment by wings110** [comment]
up

**Comment by sonninnos** [comment]
Why bother updating before 0.258? And did you test that arcade and mess subtargets still work?

**Comment by MistyDreams** [comment]
Perhaps there`s an update they want but lack the resources to compile i?. I have to agree 258 is just round the corner seems pointless doing intermediate updates when there is a monthly release schedule.

**Comment by sonninnos** [comment]
Thanks, but I got it sorted, so I'll close this.

**Pull request closed without merging**
