### PR TITLE
Add MAME menu item for Exit Game

### LINKED ISSUE #89: Pressing Esc or shift+enter (open menu) and resuming causes the MAME software list to open
Just like if we had requested the software list to open.

I'll suggest that maybe the default should be to never open the software list myself, or expose that shortcut to a retroarch binding. Same thing as mapping the coin insert.

I'm trying to find a mame.ini option to disable the softwarelist/mame GUI completely in the hope it disables the annoying reset but i haven't had much luck. Even if i do find one for disabling the gui i fear the 'reset' shortcut would remain and open it anyway.

The MAME core says these things when this happens:
```
exit scope, restart empty driver
SOURCE FILE: ../../../../../src/emu/drivers/empty.cpp
PARENT: 0
NAME: ___empty
DESCRIPTION: No Driver Loaded
YEAR: 2007
MANUFACTURER: MAME
```
As i said, i'm looking for a way to turn it into a exit. Reset can be handled from the retroarch playlist. And should, since the core obviously does a poor job of it by going from a game to a 'empty' driver.

### PR DESCRIPTION
**Pull request by GrumpyGopher**
Fix #89 add separate MAME menu item for IPT_UI_EXIT_GAME that is not set by default to prevent accidentally returning MAME Software list when being used with Retroarch

### CODE REVIEW

**Comment by inactive123** [comment]
alright, I think this is important enough to merge. however @tcamargo we will have to remember to backport this for future versions.

**Comment by tcamargo** [comment]
I always merge mame/<tag> into libretro/master so upports are automatic. You might get conflicts.

**Comment by inactive123** [comment]
Hi @tcamargo , got any idea how we could do this without getting conflicts with future rebases?

**Comment by tcamargo** [comment]
You can try to remap IPT_UI_CANCEL in osd/modules/input/input_retro.cpp. Anyway, there are more libretro modification in the changed files. So, if this changes solve a bug, just merge it. A future conflict is unlikely. If you get one, it would be easy to solve.

**Comment by GrumpyGopher** [comment]
Remapping IPT_UI_CANCEL does work but I was hoping to have a separate menu item. I have IPT_UI_CANCEL mapped to a controller button so I can navigate the Mame menu but if you press it too many times you can accidentally exit the game. With the addition of IPT_UI_EXIT_GAME this would no longer be possible.

**Comment by inactive123** [comment]
@tcamargo Do you feel comfortable with merging this? Or is there something holding it up?

**Pull request merged**
