### PR TITLE
fix makefile.libretro and add ucrt64,clang32,clang64 msys2env builds

### PR DESCRIPTION
**Pull request by grant2258**
@sonninnos there was an issue all over the makefile having quotes all over the place. I have fixed that and i have added CLANG32,CLANG64,UCRT , msys2 env builds. I have also crossed compiled with no issues using .
```
make -f Makefile.libretro SUBTARGET=pacem SOURCES=src/mame/pacman/pacman.cpp TARGETOS=windows PTR64=1 OVERRIDE_CC=x86_64-w64-mingw32-gcc OVERRIDE_CXX=x86_64-w64-mingw32-g++ OVERRIDE_LD=x86_64-w64-mingw32-ld MINGW64=/usr -j8
```

### CODE REVIEW

**Comment by joepogo** [comment]
Thanks so much for continuing to make pull requests and look at mame @grant2258 !

I had a question for you, the link you posted in the mame test thread for the uwp threading, is that the equivalent of PC threading and would it speed up our few problem games back up?

Most of us who use Xbox don't get as much help or insight from most, so it's rare to get a person like you willing to even help. 

Grateful to have gotten as much of your time as we have. Anyhow, hopefully my question doesn't bother you.

**Comment by grant2258** [comment]
Threading will always help I think libretro are aware of the issue in the source code here. https://github.com/libretro/RetroArch/blob/56e088b937bc59fa4f9f37d265c6549a84324edf/uwp/uwp_async.h#L32-L38 just to be clear in no affiliated with libretro in any way questions regarding things like this would be best answered by them they know the api inside out.

**Comment by joepogo** [comment]
Thanks for your response. Yea, I totally get what you're saying. Thankfully this issue is almost completely resolved. All games now work on mame Xbox retroarch thanks to your pull request and I couldn't be more grateful. 

Just trying to figure out what or how is the best way to try to get that library you posted dropped in so we can test that out now that we know incompatible threading was the issue. 

If libretro doesn't want or feel like trying to drop in that lib we can try a patch to test it out and compile it ourselves if someone is willing to help. 

I feel like we're 90% there. And we wouldn't be anywhere near that if you not for people like yourself. 😁

Anyways, I hope I'm not bothering you and I thank you for your time as always grant. 👊

**Comment by grant2258** [comment]
Its no problem at all @joepogo  @sonninnos  found an two issues with the make file. If your used ARCH it was not  setting LIBRETRO_CPU and the autocpu detection wasnt working at all.

**Comment by grant2258** [comment]
That the work on the makefile done all vars are passed along now and CONFIG, ARCH are protected now you can override them if you have to using the directive,  use the see toochain.lua for ARCH details

**Comment by sonninnos** [comment]
Why did you close this?

**Comment by grant2258** [comment]
I didn't I mistakenly done in in my master branch and Im checking mame0256 so I synced with libretro. I did make it in a makefile branch in case it was needed can do a fresh pull request if you like. https://github.com/libretro/mame/compare/master...grant2258:mame:makefile?expand=1

**Comment by sonninnos** [comment]
Let's sort it out after I complete the 0.255 branch merge and also 0.256, since it came out while in the limbo.

**Comment by grant2258** [comment]
Yea no rush there on my part was just minor tweaks anyway.

**Pull request closed without merging**
