### PR TITLE
version bump (mame-0.211)

### PR DESCRIPTION
**Pull request by tcamargo**
Hi, my first contribution to libretro. Simple merge of mame-0.211.

### CODE REVIEW

**Comment by inactive123** [comment]
Hi there, thanks!

Did you confirm if you can compile and link a libretro core with this that works?

**Comment by tcamargo** [comment]
Hi, yes it compiles. Please. check mame_libretro.so in https://batocera-linux.xorhub.com/users/poke-1,0/5.23/mame-0.211/.

**Comment by inactive123** [comment]
OK. What about the Travis build error?

**Comment by tcamargo** [comment]
I think it was failing before my changes. I can check it tomorrow.

**Pull request merged**
