### PR TITLE
Update 0.255

### LINKED ISSUE #346: Mame 252 files
Maybe update files to compile last mame 252? Thanks

### LINKED ISSUE #349: Mame v254 now
Hello,
maybe will be synchronized libreto mame with version 253?

### LINKED ISSUE #352: could it be synchronized with the upstream 0.254?
It has been more than 4 months since the last major version 0.251 was synchronized. We're all eagerly anticipating a new sync...

### LINKED ISSUE #373: Mame 255 update
Please 255 update
Many fix snd new entry ( namco )
More good of actual 251 bugged

### PR DESCRIPTION
**Pull request by sonninnos**
Everything should operate as before despite the input and renderer changes.

Bonus default joystick adjustments:
- Twinstick games need no configuring
- D-pad works as analog controls
- Internal UI page up/down to L1/R1

Please test and confirm that everything is fine before I merge.

Closes #346 
Closes #349
Closes #352 
Closes #373

### CODE REVIEW

**Comment by MistyDreams** [comment]
only booted 3 random games seems fine on linux with the games I tested. Just a quick variable name fix is needed will post the dif 

```
diff --git a/src/osd/libretro/retromain.cpp b/src/osd/libretro/retromain.cpp
index 97a83351fcc..9e21b8ca089 100644
--- a/src/osd/libretro/retromain.cpp
+++ b/src/osd/libretro/retromain.cpp
@@ -204,7 +204,7 @@ int mmain(int argc, char *argv[])
        // FIXME: this should be done differently
 
 #ifdef RETROMAME_UNIX
-       sdl_entered_debugger = 0;
+       retro_entered_debugger = 0;
 #if (!defined(SDLMAME_MACOSX)) && (!defined(SDLMAME_HAIKU)) && (!defined(SDLMAME_EMSCRIPTEN)) && (!defined(SDLMAME_ANDROID))  && (!defined(RETROMAME))
        FcInit();
 #endif
```

**Comment by sonninnos** [comment]
Whoops, thanks. Same thing needed just below that too, will fix asap.

**Comment by guljam** [comment]
I tried building this in msys2 mingw64 shell
(with $ make -f Makefile.libretro -j$(nproc) command)

However, during compilation, a uint type error occurred, so I had to add #include < cstdint > code to several header files.

Now I get the following error.
```
/../libretro/bin/libbgfx.a ../../../../libretro/bin/libbimg.a ../../../../libretro/bin/libbx.a . ./../../../libretro/bin/mame_mame/libocore_retro.a -luser32 -lwinmm -ladvapi32 -lshlwapi -lwsock32 -lws2_32 -lpsapi -liphlpapi -lshell32 -luserenv -lgdi32 -ldsound -ldxguid -loleaut32 -Wl ,--end-group
ld.lld: error: undefined symbol: ui::menu_select_game::force_game_select(mame_ui_manager&, render_container&)
>>> referenced by libfrontend.a(mame.o):(emulator_info::display_ui_chooser(running_machine&))

ld.lld: error: undefined symbol: ui::menu_select_game::menu_select_game(mame_ui_manager&, render_container&, char const*)
>>> referenced by libfrontend.a(mainmenu.o):(ui::menu_main::handle(ui::menu::event const*))
collect2.exe: error: ld returned 1 exit status
make[3]: *** [mame.make:519: ../../../../../mame_libretro.dll] Error 1
make[2]: *** [Makefile:1075: mame] Error 2
make[2]: Leaving directory '/e/libretro0255/mame/build/projects/retro/mame/gmake-mingw64-gcc'
make[1]: *** [makefile:1132: windows_x64] Error 2
make[1]: Leaving directory '/e/libretro0255/mame'
make: *** [Makefile.libretro:248: build] Error 2
```


The build environment followed the instructions in the libretro documentation and downloaded all dependencies and packages.

**Comment by sonninnos** [comment]
Yet I had no issues after `make clean` with msys2..

**Comment by guljam** [comment]
@sonninnos 

```
PAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DWIN32 -I"../../../../../src/osd" -I"../../../../../src/emu" -I"../../../../../src/devices" -I"../../../../../src/lib"-I"../../../../../src/lib/util" -I"../../../../../3rdparty" -I"../../../../generated/emu" -I"../../../../generated/emu/layout" -I"../../../../../3rdparty/asio/inlude" -I"../../../../../3rdparty/expat/lib" -I"../../../../../3rdparty/libflac/include"  -O2 -m64 -std=c++17 -fPIC -pipe -O3 -fno-strict-aliasing -Wno-unknown-prgmas -Wall -Wcast-align -Wformat-security -Wundef -Wwrite-strings -Wno-conversion -Wno-sign-compare -Wno-error=deprecated-declarations -Wno-unused-result -Wno-aray-bounds -Wno-error=attributes -Wno-stringop-truncation -Wno-stringop-overflow -Wno-nonnull -Wno-stringop-overread -Wno-error=maybe-uninitialized -Wno-error=uniitialized -m64 -std=c++17 -Woverloaded-virtual -Wimplicit-fallthrough -Wno-class-memaccess -Wsuggest-override -include ../../../../libretro/obj/x64/libretro/emu. -include e:/libretro0255/mame/src/osd/libretro/retroprefix.h -o "../../../../libretro/obj/x64/libretro/src/devices/machine/ie15.o" -c "../../../../../src/device/machine/ie15.cpp"
Archiving liboptional.a...
rm -f "../../../../libretro/bin/mame_mame/liboptional.a"
ar  -cs ../../../../libretro/bin/mame_mame/liboptional.a
make[2]: Leaving directory '/e/libretro0255/mame/build/projects/retro/mame/gmake-mingw64-gcc'
make[1]: *** [makefile:1132: windows_x64] Error 2
make[1]: Leaving directory '/e/libretro0255/mame'
make: *** [Makefile.libretro:248: build] Error 2
```

I get an error first
However, when I try to compile again, this error no longer appears.



the second error is same as attached image file
If I include cstdint in a few header files with the help of chatgpt, no error occurs and finally I get the linker error I described above.

haha i don't know anymore

image

**Comment by sonninnos** [comment]
I have no idea what is happening there, but it does not look right at all on many levels.. Not only because running multiple jobs at the same time makes log output a mess.

**Comment by guljam** [comment]
@sonninnos I currently built this package with path e:\libretro_0255\mame
Do I have to build by moving to the c:\mingw64 folder of the c drive or a path similar to that?

```
_USE_MIDI='1' --NO_USE_PORTAUDIO='1' --PYTHON_EXECUTABLE='python3' --osd='retro' --targetos='windows' --PLATFORM='x86' --gcc=mingw64-gcc --gcc_ve
make -R verbose=1 -C build/projects/retro/mame/gmake-mingw64-gcc config=libretro64 WINDRES=C:/msys64/mingw64/bin/windres precompile
make[2]: Entering directory '/e/libretro0255/mame'
make[2]: *** build/projects/retro/mame/gmake-mingw64-gcc: No such file or directory.  Stop.
make[2]: Leaving directory '/e/libretro0255/mame'
make[1]: *** [makefile:1131: windows_x64] Error 2
make[1]: Leaving directory '/e/libretro0255/mame'
make: *** [makefile.libretro:248: build] Error 2
```

another error occurred

code of line 1131 of the makefile... do something with build/projects/retro/mame/gmake-mingw64-gcc path and got an error.

So I was wondering if I need to specify a special path when building the package in the first place.

**Comment by sonninnos** [comment]
Uhh, all I'm doing is `make -f Makefile.libretro` like the readme says. And with `PREMAKE=0` after the first run.

**Comment by guljam** [comment]
@sonninnos  ok thanks I'll try everything again from scratch

**Comment by guljam** [comment]
@sonninnos 

I realized that the -j option causes dependency problems at compile time. Compilation of mame_libretro.dll was successful without using the -j option.
It took about 3 hours with intel 12100f cpu.


but during compilation
../../../../../src/osd/modules/monitor/monitor_module.h:32:50: error: 'std::uint64_t' has not been declared
  error: 'uint8_t' in namespace 'std' does not name a type; did you mean 'wint_t'?

An error related to the uint type occurred.

monitor_common.h
monitor_module.h
ptypes.h
osdlib.h

I had to add #include <cstdint> code to the file

I downloaded the pure mame 0.255 source file and all of the files had #include <cstdint> code

However, the above code is removed from the libretro/mame package. I don't know if it's a difference in my computer environment, but I think I need to check those 4 files.

**Comment by guljam** [comment]
@sonninnos I was completely mistaken. I didn't change the branch to 0255. I haven't built it yet, but I think it will work this time

**Comment by guljam** [comment]
I built the core without any problems thank you

**Comment by PantaRei1983** [comment]
I also built the core on Windows 11 64-bit with MSYS2 package, and testing it on latest stable version of Retroarch, testing Namco system 10 games, works like a charm. Thanks a lot!

**Comment by StormedBubbles** [comment]
Hey, thanks so much for this. These changes also compile fine on a Raspberry Pi 4B using the 32-bit Buster OS (RetroPie). I haven't done any testing further than seeing if a few games here and there work (they do).

[Here is a link](https://pixeldrain.com/u/DQvApavG) to the compiled .so in case anyone using the same OS wants to try it out before the changes get merged. A few things to note:

- There is no more `SUBTARGET=arcade`, so my understanding is that either select drivers or the entirety of MAME has to be compiled. I chose the latter and had to wait a little under 8 hours for the compilation to complete
- The resulting .so for me ended up being called `mame_libretro.so` instead of the `mamearcade_libretro.so` that I am used to dealing with in RetroPie

**Comment by tempt187** [comment]
> I also built the core on Windows 11 64-bit with MSYS2 package, and testing it on latest stable version of Retroarch, testing Namco system 10 games, works like a charm. Thanks a lot!

Could you share a link to the compiled .dll please?

**Comment by PantaRei1983** [comment]
> > I also built the core on Windows 11 64-bit with MSYS2 package, and testing it on latest stable version of Retroarch, testing Namco system 10 games, works like a charm. Thanks a lot!
> 
> Could you share a link to the compiled .dll please?

[Click here to download it from MEGA.nz](https://mega.nz/file/KZZS0RKQ#efsOGF2sVXeVq2t3nEO7cTULIQuHi0asjCxTZYpE31Q)

**Comment by PantaRei1983** [comment]
> Hey, thanks so much for this. These changes also compile fine on a Raspberry Pi 4B using the 32-bit Buster OS (RetroPie). I haven't done any testing further than seeing if a few games here and there work (they do).
> 
> [Here is a link](https://pixeldrain.com/u/DQvApavG) to the compiled .so in case anyone using the same OS wants to try it out before the changes get merged. A few things to note:
> 
> * There is no more `SUBTARGET=arcade`, so my understanding is that either select drivers or the entirety of MAME has to be compiled. I chose the latter and had to wait a little under 8 hours for the compilation to complete
> * The resulting .so for me ended up being called `mame_libretro.so` instead of the `mamearcade_libretro.so` that I am used to dealing with in RetroPie

Is it possible to compiling this for Android 64-bit OS on Win 11 64-bit? I tried it one time, but I failed... PSX arcade based games working great on my Xiaomi MI11 with Retroarch for android.

**Comment by tempt187** [comment]
> > > I also built the core on Windows 11 64-bit with MSYS2 package, and testing it on latest stable version of Retroarch, testing Namco system 10 games, works like a charm. Thanks a lot!
> > 
> > 
> > Could you share a link to the compiled .dll please?
> 
> [Click here to download it from MEGA.nz](https://mega.nz/file/KZZS0RKQ#efsOGF2sVXeVq2t3nEO7cTULIQuHi0asjCxTZYpE31Q)

Awesome! TYVM!

**Comment by StormedBubbles** [comment]
> > Hey, thanks so much for this. These changes also compile fine on a Raspberry Pi 4B using the 32-bit Buster OS (RetroPie). I haven't done any testing further than seeing if a few games here and there work (they do).
> > [Here is a link](https://pixeldrain.com/u/DQvApavG) to the compiled .so in case anyone using the same OS wants to try it out before the changes get merged. A few things to note:
> > 
> > * There is no more `SUBTARGET=arcade`, so my understanding is that either select drivers or the entirety of MAME has to be compiled. I chose the latter and had to wait a little under 8 hours for the compilation to complete
> > * The resulting .so for me ended up being called `mame_libretro.so` instead of the `mamearcade_libretro.so` that I am used to dealing with in RetroPie
> 
> Is it possible to compiling this for Android 64-bit OS on Win 11 64-bit? I tried it one time, but I failed... PSX arcade based games working great on my Xiaomi MI11 with Retroarch for android.

I'm not sure. Some kind of cross-compiling utility would be needed. I unfortunately don't have any experience with that.

**Comment by StormedBubbles** [comment]
@sonninnos I am noticing that the saved setting for the Main CPU Overclock core option is not respected upon initial boot if I use a non-default setting. I have to go into the core options, change that setting, and then exit the core options in order to see that setting take effect.

**Comment by riggles1** [comment]
@StormedBubbles That's why the core option exusts so you can save it as a game override instead, been like that for ages. MAME is against saving overclock on the default standalone MAME to reduce false bug reports, so they make you manually set it each time. (Though to verify bugs you should use a fresh mame build to confirm the issue).

**Comment by StormedBubbles** [comment]
> @StormedBubbles That's why the core option exusts so you can save it as a game override instead, been like that for ages. MAME is against saving overclock on the default standalone MAME to reduce false bug reports, so they make you manually set it each time. (Though to verify bugs you should use a fresh mame build to confirm the issue). 

Hi,

I am aware of that. Let me give more details. In the older version of lr-MAME on my computer, the slider automatically gets adjusted to the core option's value when I boot the emulator (overriding MAME's policy on saving cheats).

However, with these latest changes, the core option doesn't work like that anymore. The CPU slider is always set to 100 regardless of the core option's value when I first boot the emulator. I have to change the setting after the emulator boots in order to get the core option to take effect.

**Comment by FollyMaddy** [comment]
Hi @sonninnos,

Great work updating it to 0255 👍 .
For you guys I hope syncing with newer versions will be easy enough in the future.
Is there a plan for future syncing ?

I have given it a shot to test.
I tested the new Konami handhelds :
ktmnt3
ktmntbb 
They worked ok so I assume other new drivers will work too.
When using background overlays I tend to use "-frameskip 10" on low-end devices.
For high-end devices no framskipping would be needed.
However I found that for my high-end device needed frameskipping.
So I also tested hbf700p (msx2) for the speed.
I found that this issue has reappeared in this 0255 fork :
https://github.com/libretro/mame/issues/371
So that's definitely something that needs to be fixed.

Just as @StormedBubbles said creating the libretro-core for subtargets doesn't work :
- SUBTARGET=arcade
- SUBTARGET=mess

For low-end devices this option has to stay.
Otherwise the binary will get too big and drivers will have lower speed in the beginning and after 30 seconds will speed up to the normal speed.
Not to mention backwards compatibility with RetroPie.
The error is :
```
stack traceback:
	[C]: in function 'error'
	/home/pi/Downloads/mame-0255/scripts/genie.lua:590: in main chunk
	[C]: in upvalue 'builtin_dofile'
	[string "premake = { }..."]:109: in function 'dofile'
	[string "_WORKING_DIR        = os.getcwd()..."]:46: in function '_premake_main'
make: *** [makefile:1320: build/projects/retro/mamemess/gmake-linux/Makefile] Error 1
```

Can you have a look at above issues ?
Or would you like the issues to be added in your 0255 fork ?

After these fixes are implemented I am happy to test things again, if I can.

**Comment by grant2258** [comment]
The  SUBTARGET=arcade,  SUBTARGET=mess are thing of the past you'll need to request these upstream . The directory containing scrips/targets are whats available now.  You can select multiple source files or multiple directories for custom builds now though. 

The are also fixes in the master branch that you should merge with the 255 branch. The better max fix handling will probably fix your video issues. https://github.com/libretro/mame/compare/libretro:mame:libretro/mame-0.255...libretro:mame:master

**Comment by sonninnos** [comment]
> found that this issue has reappeared in this 0255 fork

It hasn't "reappeared", but that fix simply was added to the main branch after this branch was done, so it will be there once it is merged. And those subtarget things were removed in upstream, so they would need to be ported back here.

**Comment by FollyMaddy** [comment]
@sonninnos

>It hasn't "reappeared", but that fix simply was added to the main branch after this branch was done, so it will be there once it is merged. 

Clear !

>And those subtarget things were removed in upstream, so they would need to be ported back here.

If it is not too much to ask then that would be a really nice thing.

**Comment by HoJo215** [comment]
Its been a while and I used to build libretro mame all the time 
but now Ive been getting this error at "Archiving libprecompile.a..."

Im on Ubuntu 22.04 fully updated. build essentials, gcc-12, etc.
Have there been any new dependencies added or does somebody know whats going on?
I was trying to build 0.255 but the error happens in the master branch too.

```
Archiving libprecompile.a...
rm -f  ../../../../libretro/bin/libprecompile.a
ar  -rcs ../../../../libretro/bin/libprecompile.a ../../../../libretro/obj/x64/libretro/src/emu/drivers/empty.o 
make[3]: *** [precompile.make:525: ../../../../libretro/bin/libprecompile.a] Bus error (core dumped)
make[3]: *** Deleting file '../../../../libretro/bin/libprecompile.a'
make[2]: *** [Makefile:79: precompile] Error 2
make[2]: Leaving directory '/home/h/Downloads/mame/build/projects/retro/mame/gmake-linux'
make[1]: *** [makefile:1324: linux_x64] Error 2
make[1]: Leaving directory '/home/h/Downloads/mame'
make: *** [Makefile.libretro:246: build] Error 2
h@h-NUC11PHi7:~/Downloads/mame$
```

**Comment by sonninnos** [comment]
Use three backticks for readable output with line breaks. In any case I've never seen
`Bus error (core dumped)`, and it does not smell like anything that can be fixed in code.

**Comment by sonninnos** [comment]
The final holdup preventing the merge is the Android builds, and I have no clue how to fix that with the current buildbot requirements. Also the missing `arcade` subtarget is a major setback since Android builds use that.

This pretty much stops any future improvements I am willing and able to do with the core.

**Comment by grant2258** [comment]
Is it just th build bot you having issues ie you can compile locally fine ?  The minimum ndk that is needed is 25c

**Comment by guljam** [comment]
@HoJo215 

I've had similar problems before

The cause was that I compiled the master branch (current mame 0.246) without changing the branch to "libretro/mame-0.255". And that I used the -j4 option.

I don't know if the source code supports asynchronous compilation, but I think it's good to run "make -f Makefile.libretro" as written in the readme. It took about 3 hours and 30 minutes to compile with an intel 12100f cpu.

**Comment by grant2258** [comment]
sorry posted the in the issue instead of here. https://github.com/libretro/mame/issues/373#issuecomment-1632954526 Ive also put a pull request in for minor sdl log issue.

**Pull request merged**
