### PR TITLE
Update to 0.245

### PR DESCRIPTION
**Pull request by stuken**
This was abit of a pig to merge. Some new additions to the osd code broke linking(not fun to find after an hour of building), input descriptors location changed and the lua build scripts ordering changed causing more linking issues.

### CODE REVIEW

**Comment by kwyxz** [comment]
Does not seem to build on Linux: 

```
../../../../../src/lib/netlist/plib/ppmf.cpp: In member function ‘void plib::mfp_raw<plib::ppmf_type::INTERNAL_MSC>::convert_to_generic(void (*&)(), plib::mfp_generic_class*&) const’:
../../../../../src/lib/netlist/plib/ppmf.cpp:82:64: error: ‘ptrdiff_t’ does not name a type
   82 |                      byteptr += (m_vptr_index * static_cast<ptrdiff_t>(sizeof(void *)));
      |                                                             ^~~~~~~~~

../../../../../src/lib/netlist/plib/ppmf.cpp:5:1: note: ‘ptrdiff_t’ is defined in header ‘<cstddef>’; did you forget to ‘#include <cstddef>’?
    4 | #include "ppmf.h"
  +++ |+#include <cstddef>
    5 | 
make[3]: *** [netlist.make:2066: ../../../../libretro/obj/x64/libretro/src/lib/netlist/plib/ppmf.o] Error 1
make[2]: *** [Makefile:25: netlist] Error 2
make[2]: Leaving directory '/mnt/space/Build/mame_stuken/build/projects/retro/mame/gmake-linux'
make[1]: *** [makefile:1332: linux_x64] Error 2
make[1]: Leaving directory '/mnt/space/Build/mame_stuken'
make: *** [Makefile.libretro:242: build] Error 2
```
adding `#include <cstddef>` to line 85 `./src/lib/netlist/plib/ppmf.h` fixes it but might break things on other platforms.

**Comment by LibretroAdmin** [comment]
Could be missing a header include there for ptrdiff_t

**Comment by stuken** [comment]
@kwyxz can you verify that you are building against the right changeset?
https://github.com/stuken/mame/blob/libretro0245/src/lib/netlist/plib/ppmf.h#L84
That import is in there already and i've verified that the merged revision and the mamdev mame0245 tag revision for both ppmf.h and ppmf.cpp are identical.

**Comment by kwyxz** [comment]
@stuken lemme try again, I git cloned the latest from your repo but it's possible I accidentally went back to the wrong branch

**Comment by kwyxz** [comment]
You were right @stuken ; my sincere apologies. It builds fine on my Linux system.
@LibretroAdmin as far as I am concerned this works.

**Pull request merged**
