### PR TITLE
clean before compile

### PR DESCRIPTION
**Pull request by grant2258**
@sonninnos if you cant clear the cache just appy this can remove after the builds done

### CODE REVIEW

**Comment by sonninnos** [comment]
Nah, let's rather just remove the caches from `.gitlab-ci.yml`.

**Comment by grant2258** [comment]
sounds like a plan the build im looking at running now is still using a local cache. Will peek in now and then and see how we get on with a clean build.

**Comment by sonninnos** [comment]
Indeed is this same familiar error cache related too then:

```
Undefined symbols for architecture arm64:
  "bfm_bd1_device::AT_BLANK", referenced from:
      bfm_bd1_device::blank(int) in libbfm.a(bfm_bd1.o)
  "bfm_bd1_device::AT_NORMAL", referenced from:
      bfm_bd1_device::blank(int) in libbfm.a(bfm_bd1.o)
      bfm_bd1_device::write_char(int) in libbfm.a(bfm_bd1.o)
  "bfm_bda_device::AT_BLANK", referenced from:
      bfm_bda_device::blank(int) in libbfm.a(bfm_bda.o)
  "bfm_bda_device::AT_NORMAL", referenced from:
      bfm_bda_device::device_reset() in libbfm.a(bfm_bda.o)
      bfm_bda_device::blank(int) in libbfm.a(bfm_bda.o)
      bfm_bda_device::write_char(int) in libbfm.a(bfm_bda.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../../../../../mame_libretro_ios.dylib] Error 1
make[2]: *** [mame] Error 2
make[1]: *** [macosx_x64_clang] Error 2
```

Weird how it says `macosx_x64_clang` when `macosx_arm64_clang` would make more sense..

**Comment by grant2258** [comment]
ok removed the clean which really needs done some way, Its the first thing to check when things go wrong. The .d files can cause issues when cached. 

if that fails try add the apple platform  target flags i looked at the lvm and added the sdk versions as a guess. But it could be as simple as a clean build. I have no idea what clang is in use x86 or arm. This way the right target will be selected just get someone that knows more about apple to check the targets.

**Comment by grant2258** [comment]
> make[1]: *** [macosx_x64_clang] Error 2

its a hack in lua that can easily be fixed to say the right thing
https://github.com/libretro/mame/blob/06ca75648cd3bd09481092bde11a27920d4fde7b/makefile#L1395C1-L1399

https://github.com/libretro/mame/blob/06ca75648cd3bd09481092bde11a27920d4fde7b/scripts/genie.lua#L708

adding passing along PLATFORM=arm64 will make the ouput more readable

**Comment by sonninnos** [comment]
On a side note for some reason totally unrelated repo ppsspp fails with the same
```ld: symbol(s) not found for architecture arm64```..
https://git.libretro.com/libretro/ppsspp/-/pipelines/205300

**Comment by sonninnos** [comment]
Could you edit `.gitlab-ci.yml` while at it and comment out the cache rows for ios and tvos, so that we won't have to trigger multiple pipelines?

**Comment by sonninnos** [comment]
Cool, ready to roll then?

**Comment by grant2258** [comment]
its still getting the cache from somewhere perhaps the ci luckily ios got a clean build

**Comment by sonninnos** [comment]
Tvos now says
```
clang: error: no such file or directory: 'arm64-apple-tvos14.2'
clang: error: no such file or directory: 'arm64'
clang: error: invalid arch name '-arch -target'
make[3]: *** [../../../../libretro/obj/x64/libretro/3rdparty/lzma/C/7zAlloc.o] Error 1
make[2]: *** [7z] Error 2
make[2]: *** Waiting for unfinished jobs....
Archiving libaccess.a...
rm -f  ../../../../libretro/bin/mame_mame/libaccess.a
ar  -rcs ../../../../libretro/bin/mame_mame/libaccess.a ../../../../libretro/obj/x64/libretro/src/mame/access/acvirus.o  2>&1 > /dev/null | sed -e '/.o) has no symbols$/d'
make[1]: *** [macosx_x64_clang] Error 2
make: *** [build] Error 2
```

And maybe cache should be removed from osx-arm64 too then
```
make[3]: *** No rule to make target `/Users/gitlab/builds/FkGsyN3z/3/libretro/mame/build/projects/retro/mame/gmake-osx-clang/../../../../../src/emu/device.ipp', needed by `../../../../libretro/obj/x64/libretro/src/emu/drivers/empty.o'.  Stop.
```

**Comment by grant2258** [comment]
ill fix that pasted over the libretro cpu android-arm cache is complaining as well

**Pull request merged**
