### PR TITLE
update to current

### PR DESCRIPTION
**Pull request by r-type**

### CODE REVIEW

**Comment by r-type** [comment]
not very well tested
I only build a driver (x68k) on Linux and it works as expected at least for me.
I'm waiting the full build finish...

**Comment by inactive123** [comment]
@r-type OK, should I hold off with merging it until you have tested the full build?

**Comment by r-type** [comment]
while it compile and run fine on linux at first saw, I got  a crash in osd related to int retro_window_info::window_init(). i have to investigate why.

that said ,I have tested many games & systems on Linux and could not reproduce the crash.
i hope someone can test a windows build too.

what do you think about it  ? should we merge and fix potential problem later when someone  report issue ?

**Comment by inactive123** [comment]
@r-type I'll let you make the decision based on what you think is best.

**Comment by r-type** [comment]
OK found the odd cause of the crash.
merge and let see ...
BTW i hope we can fix buildbot for win and android ...

**Comment by inactive123** [comment]
@r-type It still doesn't compile for Windows and Android? 

Maybe I should talk to hunterk about this.

**Comment by r-type** [comment]
my own build compile fine (for both),
but for buildbot not sure if @fr500 success with android arm32
 and not sure about the state of windows build but buildbot use 
GCC 4.9.2 detected
and  log say
failed at  GCC version 5.0 or later needed

**Comment by r-type** [comment]
If this can help, 
here is the link to  my own build : Linux64 , Win64 ,  Android arm32 .
and below how I've built them.

```
linux:

make OSD="retro" verbose=1 RETRO=1 NOWERROR=1  OS="linux" TARGETOS="linux" CONFIG="libretro"  NO_USE_MIDI="1" PTR64=1 TARGET=mame -j10

win64 linux crossbuild:

export MINGW64=/usr

make OSD="retro" verbose=1 RETRO=1 NOWERROR=1 OS="linux" TARGETOS="windows" CONFIG="libretro" NO_USE_MIDI="1" PTR64=1 TARGET=mame GCC="mingw64-gcc" -j10

android arm32 linux crossbuild:

export ANDROID_NDK_LLVM="/opt/ndk/toolchains/llvm-3.5/prebuilt/linux-x86_64" 
export ANDROID_NDK_ARM="/opt/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64" 
export ANDROID_NDK_ROOT="/opt/ndk"

make OSD="retro" verbose=1 RETRO=1 NOWERROR=1  NOASM="1" gcc="android-arm" OS="linux" TARGETOS="android-arm" CONFIG=libretro NO_USE_MIDI="1"  -j10

```

http://dl.free.fr/getfile.pl?file=/kr4djpYq

**Pull request merged**
