### PR TITLE
Fix build of MAME core

### PR DESCRIPTION
**Pull request by kwyxz**
Cherry-picked commit fef64670fed6

```
netlist: Address comments from PR #9794, partially fix issue #9801 (#9805)

- added cstddef to includes in ppmf.h
- more explicit comments in ppmf.h
- Fixed more typos and improved readiability
```

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
This seems weird. Can't we just update to the latest version of MAME instead of starting to cherrypick random commits? That would make keeping this core up-to-date exceedingly difficult.

Furthermore, we need a dedicated maintainer for this core that keeps it up to date. If you'd like to take on the challenge, by all means, but we need someone at least.

**Comment by riggles1** [comment]
Not gonna lie, got excited thinking it was time for 245. Been eyeing that Megumi Rescue.

Hopefully an update follows soon enough. 
(also hoping manual rotation won't be broken next time, no dice using the .ini to have that auto rotate off like usual with pre-244. ).

Appreciate the commit though regardless!

**Comment by kwyxz** [comment]
> This seems weird. Can't we just update to the latest version of MAME instead of starting to cherrypick random commits? That would make keeping this core up-to-date exceedingly difficult.
> Furthermore, we need a dedicated maintainer for this core that keeps it up to date. If you'd like to take on the challenge, by all means, but we need someone at least.

Sorry, I cannot volunteer to maintain this whole core as I lack both time and skills for such a task. The only point of this commit was to allow building the core again while deviating as minimally as possible from upstream, hence the cherry-pick. I understand your point, though. Feel free to close this pull request if it introduces more problems than it solves.

**Comment by LibretroAdmin** [comment]
@kwyxz I suppose we could merge this for now until someone pushes the MAME core to the next proper version. It's better than absolutely nothing.

**Comment by LibretroAdmin** [comment]
@stuken Would you perhaps be interested in updating the MAME core to the latest version? If so, merging this PR is perhaps not necessary since it would come included.

**Comment by LibretroAdmin** [comment]
@stuken mentioned that some of the Lua script changes proves troublesome in updating to the latest MAME version.

@stuken Could you perhaps explain to @tcamargo where you are stuck? Maybe together this challeng can be overcome.

**Comment by kwyxz** [comment]
I'm confident #317 will eventually take care of this. Closing.

**Pull request closed without merging**
