### PR TITLE
Use libretro screen rotation

### LINKED ISSUE #234: Vertical games with zfast-crt shader
On current MAME 0.229 Core, the vertical games using zfast-crt shaders do not autocorrect the shader to show vertical scanlines like MAME 2003+ and FBNeo do.

Screenshots:
MAME 2003+
Captura de tela de 2021-02-24 19-48-04
Captura de tela de 2021-02-24 19-48-36
Captura de tela de 2021-02-24 19-48-52

MAME 0.229
Captura de tela de 2021-02-24 19-50-27
Captura de tela de 2021-02-24 19-52-11
Captura de tela de 2021-02-24 19-53-48

### LINKED ISSUE #261: missing libretro auto-rotation implementation
This core doesn't implement libretro's auto-rotation, instead it internally rotates the framebuffer of vertical games and present it to the libretro api saying "this game is horizontal". It's causing improper behavior with shaders and maybe some other libretro features.

This is how a shader like zfast-crt currently looks on this core : 

This is how it should look, because a vertical game is a game with a physically rotated screen, meaning the scanlines must be rotated too : 

Note that, afaik, mame and mame2016 are the 2 only cores handling arcade vertical games behaving wrongly

### PR DESCRIPTION
**Pull request by sonninnos**
Offload rotation to frontend if allowed with `video_allow_rotate`. Also fixed alternate renderer for seamless toggling and for it to not trigger video change on any option change, and cleaned up unused and unnecessary stuff.

Closes #261 
Closes #234

### CODE REVIEW

**Comment by MistyDreams** [comment]
Issues are still valid from #261 load othunder, kick disc of tron or any other mirrored game. Not an ideal situation its a rotation RA cant support so a on off switch for libretro rotation or check the rotation flags to automate so people can play these games. I dont think this warrants another issue to be opened. The op (ghost) explained the this issue would happen in #261 looks like he was correct.

**Comment by sonninnos** [comment]
Yes, I have a new rotation core option ready with 3 modes: libretro, internal, none. Not sure how to do mirroring only with libretro, but at least it can be toggled easily instead of disallowing libretro rotation.

**Comment by MistyDreams** [comment]
Swaps are handled by iterating over input(image) backwards on the x or y for both for swapxy but the other rotations handle that fine. I have no idea if its something RA would include or not though.

**Comment by sonninnos** [comment]
I simply forced flipping when internal rotation is disabled, and all cases should be good now.

**Comment by MistyDreams** [comment]
That could be an issue will try test when i get time as flipx and flipy will be set for normal rotations.

https://github.com/libretro/mame/blob/65395ba8037317ffadacb6ff6833b251794b810f/src/emu/emucore.h#L187-L197

Ive just glanced at it but the flip probably only needs applied if rot != 0 90 180 270 to alow libretro to do the available ones it can support.

**Comment by sonninnos** [comment]
That is what it is doing.

**Comment by MistyDreams** [comment]
I was looking at this change diff instead of the other one I think this code could be simplified though but if its works it works. I simply meant, if you reverse 0 90 180 270 flags and any are left over let mame handle it. This way even if using libretro rotation so users wont need to switch just to be clear.

**Comment by riggles1** [comment]
Once this is implemented, what will become the optimal settings for this use case? (Just caught wind of this change so haven't looked into it further)

CRT monitor in an arcade machine that you manually rotate for vertical games.

A long time ago I would have to set RA as don't allow rotation iirc. But nowadays I have to go into mame config for every new vertical I play (just once).

From the sounds of it this fixes that problem, which is very appreciated! : D

**Comment by MistyDreams** [comment]
How do you want vertical games work the way the show in the original arcade ? Right now it rotates to the screen orientation if you want it like the original a tate mode option would need to be added. I think ill need to compile this not sure how long the build bot will take but its nice to see some progress.

**Comment by riggles1** [comment]
Yes, as I'm using a CRTEmudriver+CRTSwitchres, so I don't want any software rotation, as rotation is handled by physically rotating the display. 

The way it's been working recently is that when you start a (new) vertical game it'll try squash itself as vertical on a horizontally oriented CRT (making switchres wrongly output 480i because of the resolution).

So I have to half blindly navigate the mame quick menu (since the menu is squashed), to set rotation within mame.

Shortly explained I don't want either RA or MAME to rotate anything. A vertical 340x240 game should output just that.

**Comment by MistyDreams** [comment]
It wont do what you want to do at the moment, it can be added though seen old code  tate mode was removed, It doesn't seem like is was hooked up though.

**Comment by MistyDreams** [comment]
@sonninnos I compiled and did a check only is issues are with ORIENTATION_SWAP_XY games ladyfrog, kick ect the games are still mirrored so not rotated and the aspect ratio is fine though. Only tested default settings with libretro rotations as this is what most people will be using. There is also only focus on alt renderer off. There is an issues put alt renderer on and start mappy with a shader and the game wont play when you start it. I dont think this was introduced by your changes though the window creation is setting up at the place as far as i can see.

Below is a fix for this I dont like walking over other peoples work its up to you how you want to work around it. 

```
diff --git a/src/osd/libretro/libretro-internal/retro_init.cpp b/src/osd/libretro/libretro-internal/retro_init.cpp
index 2dafb1610c7..0e67c73e435 100755
--- a/src/osd/libretro/libretro-internal/retro_init.cpp
+++ b/src/osd/libretro/libretro-internal/retro_init.cpp
@@ -490,10 +490,13 @@ static int execute_game(char* path)
 
    if (rotation_mode == 2 && environ_cb(RETRO_ENVIRONMENT_SET_ROTATION, &screenRot))
    {
-      rotation_allow = 1;
-      Add_Option((char*)"-norotate");
-      norotate = true;
-   }
+      if ( gameRot !=  ORIENTATION_SWAP_XY ) // RA can not handle x/y mirror
+      {
+        rotation_allow = 1;
+        Add_Option((char*)"-norotate");
+        norotate = true;
+      }
+  }
    else if (rotation_mode == 1 || rotation_mode == 2)
    {
       rotation_allow = 0;
```

**Comment by MistyDreams** [comment]
@riggles1 norotate will work for most of your needs accept a few xyswap games. A switchres mode with -rotate and -autoror or -autorol depending on your rotation preference for vertical direction would be ideal  for the switchres setup (libretro rotates for vertical are only needed for shader scanline direction).

 If you know how to use a mame ini with this  core set option in the new code as rotation as internal(latest code) and set autorol or autoror in the mame  ini. youll have no issues with any game and all vertical games will rotate the same direction.

**Comment by riggles1** [comment]
Thanks a lot! Will give that a go, it's not the biggest issue there is, but still an inconvenience that rotations couldn't be turned off so it's all manual (as in vertical games should always be oriented according to the physical screen). 

mame.ini usage is standard use here anyway to get mame where you want it, always helping people out setting this up for CRT usage since I made tutorials for that stuff. Again, super great!

**Comment by sonninnos** [comment]
Ok, ladyfrog is covered with https://github.com/libretro/mame/pull/367

**Comment by MistyDreams** [comment]
good job, its a nice use of flips. A -rotate and -autotror  or autorol and a libretro rotation would handle libretro  vertical games and with no rotation would handle tate. If tate is something your interested in adding. The support is in though and that the main thing jon well done.

**Comment by sonninnos** [comment]
I thought "tate" was also already handled with https://github.com/libretro/mame/pull/364

**Comment by MistyDreams** [comment]
tate mode is where the user physically rotates the monitor its should orient the display cw or ccw for all cases. No rotate will handle most but 270 and 90 will sway a different ways and a the xy swaps wont work with the mirrors.  The rotate and -autoror or -autorol will work for all cases and libretro could just flip the verticals and the tate mode leave it as per rotation chosen.  Its easy enough to just add another rotation mode for this but it could work for both.

**Pull request merged**
