### PR TITLE
fix android builds

### PR DESCRIPTION
**Pull request by grant2258**
Fix the android builds to link properly has been tested

### CODE REVIEW

**Comment by sonninnos** [comment]
Thanks. Once this clears out I guess we can put all the caches back on.

Too bad arm64 versions didn't like adding that `-fsigned-char`, so can't know if it helps or not with certain problem machines, like "outfxies".

**Comment by sonninnos** [comment]
Hmm, now Windows and Linux fail with:
```
/builds/libretro/mame/scripts/toolchain.lua:535: attempt to concatenate a nil value
stack traceback:
	/builds/libretro/mame/scripts/toolchain.lua:535: in function 'toolchain'
	/builds/libretro/mame/scripts/genie.lua:1220: in main chunk
	[C]: in upvalue 'builtin_dofile'
	[string "premake = { }..."]:109: in function 'dofile'
	[string "_WORKING_DIR        = os.getcwd()..."]:46: in function '_premake_main'
makefile:1132: recipe for target 'build/projects/retro/mame/gmake-mingw64-gcc/Makefile' failed
make[1]: *** [build/projects/retro/mame/gmake-mingw64-gcc/Makefile] Error 1
```

**Comment by grant2258** [comment]
its ok it lua i know whats causing it. The target has changed for android with not source changes youll need to do clean builds. Older builds where compiled with aarch64-none-linux-android and new ones are aarch64-linux-android for all builds since there are no code changes it wont recompile with the right flags and options

**Comment by grant2258** [comment]
just tested mame0257 is a clean merge no issues on linux :)

**Pull request merged**
