### PR TITLE
xbox threads test core option

### PR DESCRIPTION
**Pull request by grant2258**

### CODE REVIEW

**Comment by greenchili2** [comment]
I was able to try a test build that someone was able to compile ( Gabo? ) on the Xbox Series X and this did the trick!  Every game with discrete sound that I tried worked.  I tried 59 of 176 parent rom sets.  A few I had to update the romsets due to the changes in the jump to 0.255.

Suffice it to say "I'm getting it on like Donkey Kong".

**Comment by greenchili2** [comment]
I just tried cruis'n USA and it crashes... I did a search and I noticed the SDLMAME_EMSCRIPTEN defines are checked in the VIDEO.CPP file.. as well as some OSD source files related to retroarch.  So more investigation may be needed to find a better way to do this.  In the meantime if we could try something with the threading turned off in the video code as well.  That would be great!

**Comment by joepogo** [comment]
Yea, i havent been able to test yet but i can confirm through greenchili this toggle will fix some of the games, def the discrete sound core games. 

Once i get home ill be able to test ibara, mmmpork and the others to see if they load as well. 

Thanks so much with everything you have done so far @grant2258 ! This is def moving in the right direction. :0

**Comment by grant2258** [comment]
well just tested the theory that was presented glad you guys can play a new game. I cant really work in hardware I dont have else I could make more progress on it. Im not sure how compatible mingw is with winrt either from what ive read its not implemented. I could try doing a mingw ucrt build not sure if it will work though would require a few changes as its all setup for mingw32 and mingw64. If i get the time ill look into it. I was just testing the threading theory @barbudreadmon posted. Its good to rule things out in a practical way at the very least at least you have a few new games to play.

**Comment by sonninnos** [comment]
So is this ready for merge then?

Not really a fan of the current core option placement since it is between display related things, but it can always be moved later, so not that important.

**Comment by joepogo** [comment]
Yea! It's ready I think. Most games are working now! I'm working on a list to post in the issue ticket but I can def say go for it @sonninnos ! :)

**Comment by sonninnos** [comment]
Ok, let's go then.

**Pull request merged**
