### PR TITLE
Fix mouse buttons, add players 7–8, add multimouse/lightgun

### PR DESCRIPTION
**Pull request by StormedBubbles**
Hello,

**EDIT ON APRIL 21: MORE ADDITIONS LISTED IN COMMENT BELOW**

This should fix issues #79, #282, and #290. 

I found that the right mouse button wasn't activated and that the middle mouse button was missing entirely. I resolved those issues in the code.

I also added support for up to 4 mice or 4 lightguns. Is that enough of each? I can't think of a game that uses more than 3 lightguns. I know of Atari's "Football" using 4 trackballs and "Sprint 8" using 8 steering wheels, so if 4 of either isn't enough, it's a quick adjustment to a few numbers here and there to increase that threshold.

Each mouse has 3 unique buttons to that player, while each gun has 2 unique buttons to that player. I also made it so that, while using a lightgun, the cursor will glue to the top-left of the screen while the gun is offscreen so that reloading doesn't fail. In addition, I also activated the optional "Gun Reload" Libretro input so that players can use button reload for any game instead of needing to point offscreen. The cursor will return to its previous position after the reload button is pressed.

**I am not sure if this is intended behavior or a glitch, but I find that having a controller stick mapped as the mouse/gun X axis and a controller active in that particular port prevents that player from using a mouse to move along the X axis. You either have to set that port's joypad device to N/A or delete the controller-stick mapping from the X axis. Nothing in the code jumped out to me as causing this behavior.**

EDIT: The bolded issue above may have just been the result of me having a controller connected that had minor drifting issues.

### CODE REVIEW

**Comment by StormedBubbles** [comment]
The mice/lightguns seem to work fine in game, but I am noticing that the MAME UI is sticking the mouse cursor to the center of the screen. Previously, it worked fine. I suspect it has something to do with this portion of the code in src/osd/modules/input/input_retro.cpp:

```
        static int vmx[4], vmy[4], ovmx[4], ovmy[4];
		 vmx[i]=fb_width/2;
		 vmy[i]=fb_height/2;
		 ovmx[i]=fb_width/2;
	     ovmy[i]=fb_height/2;

         vmx[i]+=mouse_x[i];
         vmy[i]+=mouse_y[i];
         if(vmx[i]>fb_width)vmx[i]=fb_width-1;
         if(vmy[i]>fb_height)vmy[i]=fb_height-1;
         if(vmx[i]<0)vmx[i]=0;
         if(vmy[i]<0)vmy[i]=0;
         if(vmx[i]!=ovmx[i] || vmy[i]!=ovmy[i]){
	        int cx = -1, cy = -1;
	        auto window = osd_common_t::s_window_list.front();

	        if (window != nullptr && window->renderer().xy_to_render_target(vmx[i], vmy[i], &cx, &cy))
					machine.ui_input().push_mouse_move_event(window->target(), cx, cy);
```

I thought this might allow any mouse to control the UI, but it appears to make the mice fight for control instead. I will see if I can resolve that.

In standalone MAME, does only the first mouse have control over the UI?

**Comment by riggles1** [comment]
Will try when I get the chance to, thanks for looking into this!

**Comment by StormedBubbles** [comment]
Which platform do you use? I am in the process of compiling some tests for Raspberry Pi 4 and can just provide the resulting .so if you're using a Pi too if you want to test. It beats waiting ~3 hours for this to compile 😀

I am increasing the player count (joypad, mouse, lightgun) to 8 in order to account for whatever possibilities games may bring. At least Sprint 8 has the capability of using 8 joypads or 8 mice. I also discovered a typo in my edits for the pointer/touchscreen mode that I fixed. I will test those results and then append to this pull request.

The mouse UI issue is confusing me. I did notice an extraneous piece of code, so hopefully that was the issue.

**Comment by StormedBubbles** [comment]
OK, I increased the player count to 8 among joypad, mouse, and lightgun. This means that up to 8 of any of those devices is now allowed. Each joypad has the full suite of controller buttons, each mouse has 3 buttons, and each lightgun has 2 buttons.

I also mapped the remaining coin/start buttons up to player 8 in the default mappings.

I tried but failed to activate the left mouse button's double click in the MAMEUI by porting over the corresponding code from `/src/osd/modules/input/input/input_sdl.cpp`.

The mouse movement (mouse 1 only) is working again in the MAMEUI, but the movement is jittery. This is confusing to me because I didn't actually change anything with that other than switching `mouse_x` and `mouse_y` to `mouse_x[0]` and `mouse_y[0]` to account for the presence of multiple mice. 

Anyway, I hope that this is satisfactory! I compiled on a Raspberry Pi 4B using RetroPie. I can provide a link to the .so in case anyone with the same system wants to test and doesn't want to wait 3–5 hours for the compilation to finish 😀.

**Comment by riggles1** [comment]
Awsome! I'm using it on windows however (I prefer it over standalone mame due to differences in Switchres CRTemudriver as well as features like the DSP equalizers and other sound things, setting such per game). Thanks again for looking into this :D

**Pull request merged**
