### PR TITLE
Building in vs2015

### LINKED ISSUE #26: Building with microsoft tools
Upstream mame can be compiled with msbuild from command line (`MSBUILD=1`) or from visual studio 2015 (`vs2015`). Neither of these seems to work for libretro mame. twinaphex said @bparker06 managed to make the buildbot use visual studio. Is there any info on that?

If no one did that for mame, can someone give me hints on how to change the makefiles to make it work?

The first error that appears is that it's missing `unistd.h` in `osdlib_retro.cpp`. The msbuild way hasn't even been considered since it's a unix header, and no way to skip it has been given in the code.

### PR DESCRIPTION
**Pull request by vadosnaprimer**
This fixes #26. Everything is explained in the commit messages. Dropping portaudio isn't required for vs build, it was just a nice bonus. Let me know if some of libretro's target systems require portaudio.

This was tested after building from both vs2015 (debug and release) and gcc (only release).

### CODE REVIEW

**Comment by zeromus** [comment]
This will help us collaborate on getting serialization working, and work on detailed synch stability and serialization issues with mame upstream.

**Comment by inactive123** [comment]
We have no need for portaudio, no. We have pretty much equivalent low-level audio drivers for every one of the APIs portaudio supports integrated in RetroArch, and it was more or less feature complete since 2011. The only one that was missing up until recently was WASAPI, but even that has now been added with a bounty. And yeah, stuff like portaudio is frontend territory anyway. A core needs to be only concerned with pushing samples to a callback function and that is it, no more required.

**Comment by r-type** [comment]
@zeromus  ???? I do not understand the sentence and the relationship with this commit

**Comment by zeromus** [comment]
Bizhawk developers aren't going to develop on this core unless they can do it in visual studio. Now that they can, they will.. or at least, they fully intend to.

**Comment by vadosnaprimer** [comment]
@r-type we need mame to send savestate buffer to the client, like it does in mame2003 build. That's our serialization goal to make it tasable. And bizhawk is VS only, so yeah, to debug comfortably we need msbuild.

@twinaphex any more suggestions on what to drop?

**Pull request merged**
