### PR TITLE
Link libgcc statically on Linux

### PR DESCRIPTION
**Pull request by jstolarek**
A speculative fix for #137 - let's see what Travis says.

### CODE REVIEW

**Comment by jstolarek** [comment]
Ok, so Travis is broken for reasons not related to this PR. Can any of the devs verify that this is a correct fix and merge it?

**Comment by tcamargo** [comment]
CI is broken. Did you test it?

**Comment by jstolarek** [comment]
I am getting (almost) the same errors on my machine as the CI throws:

```
Building driver list...
In file included from ../../../../../src/osd/libretro/retromain.cpp:24:
../../../../../src/osd/libretro/osdretro.h:26:6: error: "USE_XINPUT" is not defined, evaluates to 0 [-Werror=undef]
 #if (USE_XINPUT)
      ^~~~~~~~~~
../../../../../src/osd/libretro/retromain.cpp:80:6: error: "USE_XINPUT" is not defined, evaluates to 0 [-Werror=undef]
 #if (USE_XINPUT)
      ^~~~~~~~~~
36794 driver(s) found
Compiling generated/mame/mame/drivlist.cpp...
../../../../../src/osd/libretro/libretro-internal/libretro.cpp: In function ‘size_t retro_serialize_size()’:
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:710:56: error: ‘class save_manager’ has no member named ‘state_size’; did you mean ‘save_item’?
    mame_machine_manager::instance()->machine()->save().state_size() > 0)
                                                        ^~~~~~~~~~
                                                        save_item
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:711:62: error: ‘class save_manager’ has no member named ‘state_size’; did you mean ‘save_item’?
   return mame_machine_manager::instance()->machine()->save().state_size();
                                                              ^~~~~~~~~~
                                                              save_item
../../../../../src/osd/libretro/libretro-internal/libretro.cpp: In function ‘bool retro_serialize(void*, size_t)’:
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:717:56: error: ‘class save_manager’ has no member named ‘state_size’; did you mean ‘save_item’?
    mame_machine_manager::instance()->machine()->save().state_size() > 0)
                                                        ^~~~~~~~~~
                                                        save_item
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:718:63: error: ‘class save_manager’ has no member named ‘write_data’; did you mean ‘write_file’?
   return (mame_machine_manager::instance()->machine()->save().write_data(data, size) == STATERR_NONE);
                                                               ^~~~~~~~~~
                                                               write_file
../../../../../src/osd/libretro/libretro-internal/libretro.cpp: In function ‘bool retro_unserialize(const void*, size_t)’:
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:724:56: error: ‘class save_manager’ has no member named ‘state_size’; did you mean ‘save_item’?
    mame_machine_manager::instance()->machine()->save().state_size() > 0)
                                                        ^~~~~~~~~~
                                                        save_item
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:725:63: error: ‘class save_manager’ has no member named ‘read_data’; did you mean ‘read_file’?
   return (mame_machine_manager::instance()->machine()->save().read_data((void*)data, size) == STATERR_NONE);
                                                               ^~~~~~~~~
                                                               read_file
../../../../../src/osd/libretro/libretro-internal/libretro.cpp: In function ‘void* retro_get_memory_data(unsigned int)’:
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:756:49: error: ‘class device_memory_interface’ has no member named ‘num_spaces’; did you mean ‘has_space’?
    for ( space_index = 0 ; space_index < memory.num_spaces() ; space_index++)
                                                 ^~~~~~~~~~
                                                 has_space
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:761:10: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
       if ( entry.m_read.m_type == AMH_RAM )
          ^
../../../../../src/osd/libretro/libretro-internal/libretro.cpp: In function ‘size_t retro_get_memory_size(unsigned int)’:
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:785:49: error: ‘class device_memory_interface’ has no member named ‘num_spaces’; did you mean ‘has_space’?
    for ( space_index = 0 ; space_index < memory.num_spaces() ; space_index++)
                                                 ^~~~~~~~~~
                                                 has_space
../../../../../src/osd/libretro/libretro-internal/libretro.cpp:790:10: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
       if ( entry.m_read.m_type == AMH_RAM )
          ^
cc1plus: all warnings being treated as errors
make[2]: *** [mame.make:570: ../../../../linux_gcc/obj/x64/Release/src/osd/libretro/libretro-internal/libretro.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[2]: *** [mame.make:574: ../../../../linux_gcc/obj/x64/Release/src/osd/libretro/retromain.o] Error 1
make[1]: *** [Makefile:1114: mame] Error 2
make: *** [makefile:1370: linux_x64] Error 2
```

**Comment by inactive123** [comment]
Would you like me to merge this regardless of Travis? It might well just compile a build just fine on our buildbot.

**Comment by jstolarek** [comment]
I would appreciate that.

BTW why is CI broken?

**Comment by jstolarek** [comment]
@twinaphex any update on this?

**Comment by inactive123** [comment]
Alright, let's give it a try.

**Comment by guoyunhe** [comment]
This PR breaks build on Linux. See #142

**Pull request merged**
