### PR TITLE
rewind support, romload freeze fix, and two other overflows fixed

### PR DESCRIPTION
**Pull request by ghost**
There was several issues the font end message had to go because it was calling before the video initialized. Someone pointed out problems I didnt know about on this core and they have been long term. auto save and load are working as well. I recommend you use the alt render at 1080p just its personal choice at the end of the day. Netplay should work as well since this core has mapping like fbneo on by default as long as people stick that mapping and dont fiddle its an option if your interested.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
@Cthulhu-throwaway i was discussing this PR on reddit, my understanding is that RA is able to do both traditional and rollback netplay, how do you figure whichever is in use ?

**Comment by ghost** [comment]
iI think this is core info files that define this I know rewind doesnt work when the states are disabled in it.  Be sure to disable the info cache in the core settings for changes to work straight away.

https://github.com/libretro/mame/blob/fcacbc7811a9b69874fd09b91e7217e44c6a0980/src/osd/libretro/libretro-internal/libretro.cpp#L801-L824 is wherre the sterilisation code is

**Comment by barbudreadmon** [comment]
I did some investigation.

The info file is indeed used to set a variable called `savestate_support_level`, which is then used in https://github.com/libretro/RetroArch/blob/master/core_info.c#L2813, afterward this function is used at https://github.com/libretro/RetroArch/blob/master/network/netplay/netplay_frontend.c#L8453 to determine if rollback netplay is available or not, with the possibility for the core to use the `RETRO_ENVIRONMENT_SET_SERIALIZATION_QUIRKS` api call to override behavior, which i don't think this core is using.

So it appears rollback netplay is enabled if you set this value to deterministic. As mentioned on reddit, savestate support isn't gonna be equal from a MAME driver to another (which is where you might want to use the serialization quirk api call to disable/enable rollback netplay on a per game/system basis). Which games did you test ? I'd recommend testing games from a variety of systems

**Comment by ghost** [comment]
I didnt do much testing on netplay at all dont know much about it. Rewind is where I done testing. Since fbneo doesnt have this information available its a report by basis on github. I suppose an option to allow or disallow option may be a more reliable solution and people can report issues with savestates that way. 

I found the random supported games did work fine with rewind could potentially be disabling working games for net-play if it works as intended.  The way i read the code the info file decides this information.  If its an issue live with rewind  working not. Hopefully someone that know can can peek at it and that will help with updating the docs.

@barbudreadmon  there is also retro_memory how would I test this feature?

**Comment by barbudreadmon** [comment]
It is to expose emulated machine's ram, it can then be used to :
- load/save "save ram" (i.e nvram), but i'd recommend leaving MAME handle that internally
- use frontend's feature to inject cheats into memory, as an alternative to the internal emulator cheat engine
- expose ram for retroachievement (trophies)

There isn't a recipe that will work everywhere, FWIW you can look at my implementation in https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/retro_memory.cpp . I'm calling `CheevosInit()` after initializing a game, which will use FBNeo's savestate system to search and expose the important ptrs. Note that there are 2 ways to do this (and i use both on a per-system basis, see `StateGetMainRamAcb`), through `retro_get_memory_data` to expose 1 single ptr, or through the `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` api call which will expose a map containing several ptrs

**Comment by ghost** [comment]
Thanks for the information just wondering. I agree a one shoe fits all especially for so many different systems. Main cpu ram seems like a sane way to go about it.

**Comment by ghost** [comment]
RetroArch does not have non-rollback netplay at all; you can try forcing savestate_support_level to "deterministic" in the core info files (stability and security issues at your own discretion), but you still need savestates for synchronization and you will still rollback, likely very often due to the lack of determinism.

NOTE: I am retired from RetroArch's development and to avoid confusion with me not replying back to mentions, I've logged back in to delete this throwaway account, which was created solely for the purpose of contributing to RetroArch.

**Comment by ghost** [comment]
So save states would allow both not sure of the differences though.  That`s the way I read the code for info file serialisation or deterministic. 

I think we can handle both not sure of the technical difference though.  All i know is rewind and auto load work, If both work and deterministic is a security risk might be wise to use serialisations. 

Seems nothing needs changed for testing which is good. I think you know more about this deterministic thing than me. You can set it whichever way prefer.

https://github.com/libretro/libretro-core-info/blob/90eff5d4e72db1b5929af7210c9b665c33034536/mame_libretro.info#L19-L20

Thanks for the calcification of setting the mode setting clears things up.

**Comment by barbudreadmon** [comment]
>You can set it whichever way prefer.

From my point of view, having the core flagged as being deterministic (i.e netplay/runahead compatible), while the savestate support is partial and hasn't been thoroughly tested, will expose a lot of problems. Expect a lot of bug reports. I'd say it's up to the people maintaining this core to decide if they want to go down that route.

**Comment by ghost** [comment]
Well thats always libretros call. Im just putting a patch in to fix issues.

I have no strong feelings on the any them. I never knew about the deterministic. A partial save support would probably be wise for both cores as any one game could flip on a technical level. 

Just because one  advertises specific cases where the states work doesnt mean they dont even the warning in mame says it may not work correctly not that it doesn't.  Setting it to partial would most likely disable rewind and net-play but would need to check.

**Comment by barbudreadmon** [comment]
The current "serialized" value is supposedly enough for rewind support : https://github.com/libretro/RetroArch/blob/master/core_info.c#L2799-L2811

**Comment by ghost** [comment]
> The current "serialized" value is supposedly enough for rewind support : https://github.com/libretro/RetroArch/blob/master/core_info.c#L2799-L2811

yeap mentioned above here https://github.com/libretro/mame/pull/329#issuecomment-1270160505 

It should be acceptable for netplay as well its just a choice deterministic  has security risks involved i would have to agree. I dont know much about it that's just down to a personal choice as it would both ways apparently.  I cant keep on arguing cases about perceived issues, Im sure if there is interest someone who knows what they doing will do the the testing if interested.  Maybe there is no interest in netplay and runahead who knows we have rewind anyway.

**Pull request merged**
